/**
 * Prebuild step — writes two tiny slug-only modules so App.js can generate
 * its <Route> list without eagerly importing the full landing-page/guide
 * content (~1.5 MB of copy across landingPages.js + its generated/Maryland
 * batches + guides.js) into the main bundle. The full content is still
 * imported normally, just inside the already-lazy LandingPage/BlogPostPage
 * components, so it only loads when one of those routes is actually visited.
 *
 * Uses the same strip-imports-and-vm-eval approach as scripts/prerender.js
 * (no Babel/webpack needed, runs on plain Node).
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");

const plain = (file) =>
  fs
    .readFileSync(path.join(ROOT, file), "utf8")
    .replace(/^\s*import[^\n]*\n/gm, "")
    .replace(/export\s+const/g, "const")
    .replace(/export\s+/g, "");

function loadLandingPageSlugs() {
  const src = [
    "src/lib/data.js",
    "src/lib/landingPagesGenerated.js",
    "src/lib/marylandPages.js",
    "src/lib/marylandPagesBatch3.js",
    "src/lib/marylandPagesBatch4.js",
    "src/lib/marylandPagesBatch5.js",
    "src/lib/landingPages.js",
  ]
    .map(plain)
    .join("\n");
  const ctx = { console };
  vm.runInNewContext(`${src}\nthis.__slugs = Object.keys(LANDING_PAGES);`, ctx);
  return ctx.__slugs;
}

function loadGuideSlugs() {
  const src = plain("src/lib/guides.js");
  const ctx = { console };
  vm.runInNewContext(`${src}\nthis.__slugs = GUIDES.map((g) => g.slug);`, ctx);
  return ctx.__slugs;
}

// Lightweight { slug: { h1 } } / [{ slug, title }] extracts for <Breadcrumbs>,
// which otherwise has to import the FULL landing-page (~1.5 MB) and blog-post
// (~500 KB) content objects just to read one title field per page — and gets
// pulled eagerly into main.js because Breadcrumbs is rendered by Layout on
// every route. Same field shape breadcrumbTrail() already expects, so the
// component itself only needs a new import source, not new logic.
function loadLandingPageTitles() {
  const src = [
    "src/lib/data.js",
    "src/lib/landingPagesGenerated.js",
    "src/lib/marylandPages.js",
    "src/lib/marylandPagesBatch3.js",
    "src/lib/marylandPagesBatch4.js",
    "src/lib/marylandPagesBatch5.js",
    "src/lib/landingPages.js",
  ]
    .map(plain)
    .join("\n");
  const ctx = { console };
  vm.runInNewContext(
    `${src}\nthis.__titles = Object.fromEntries(Object.entries(LANDING_PAGES).map(([slug, p]) => [slug, { h1: p.h1 }]));`,
    ctx
  );
  return ctx.__titles;
}

function loadBlogPostTitles() {
  const src = [
    "src/lib/blogPostsBatch2.js",
    "src/lib/blogPostsBatch3.js",
    "src/lib/blogPostsBatch4.js",
    "src/lib/blogPostsBatch5.js",
    "src/lib/blogPostsBatch6.js",
    "src/lib/blogPostsBatch7.js",
    "src/lib/blogPostsGenerated.js",
    "src/lib/blogPosts.js",
  ]
    .map(plain)
    .join("\n");
  const ctx = { console };
  vm.runInNewContext(
    `${src}\nthis.__titles = BLOG_POSTS.map((p) => ({ slug: p.slug, title: p.title }));`,
    ctx
  );
  return ctx.__titles;
}

function loadGuideTitles() {
  const src = plain("src/lib/guides.js");
  const ctx = { console };
  vm.runInNewContext(`${src}\nthis.__titles = GUIDES.map((g) => ({ slug: g.slug, title: g.title }));`, ctx);
  return ctx.__titles;
}

function writeSlugModule(outFile, exportName, slugs) {
  const banner =
    "// AUTO-GENERATED by scripts/generateRouteSlugs.js (runs as a prebuild/prestart step).\n" +
    "// Do not hand-edit — it is overwritten on every build. Slugs only, no page\n" +
    "// content, so App.js can build its <Route> list without pulling the full\n" +
    "// (large) content objects into the eager main bundle.\n";
  const body = `${banner}export const ${exportName} = ${JSON.stringify(slugs, null, 2)};\n`;
  fs.writeFileSync(path.join(ROOT, outFile), body);
}

const landingSlugs = loadLandingPageSlugs();
const guideSlugs = loadGuideSlugs();
const landingTitles = loadLandingPageTitles();
const blogTitles = loadBlogPostTitles();
const guideTitles = loadGuideTitles();

writeSlugModule("src/lib/landingPageSlugs.js", "LANDING_PAGE_SLUGS", landingSlugs);
writeSlugModule("src/lib/guideSlugs.js", "GUIDE_SLUGS", guideSlugs);
writeSlugModule("src/lib/landingPageTitles.js", "LANDING_PAGE_TITLES", landingTitles);
writeSlugModule("src/lib/blogPostTitles.js", "BLOG_POST_TITLES", blogTitles);
writeSlugModule("src/lib/guideTitles.js", "GUIDE_TITLES", guideTitles);

console.log(
  `[generateRouteSlugs] wrote ${landingSlugs.length} landing-page slugs, ${guideSlugs.length} guide slugs, ` +
    `${Object.keys(landingTitles).length} landing titles, ${blogTitles.length} blog-post titles, ${guideTitles.length} guide titles.`
);
