import "@/App.css";
import { Suspense, lazy } from "react";
import { BrowserRouter, Routes, Route, Navigate, useLocation } from "react-router-dom";
import { Toaster } from "@/components/ui/sonner";
import Layout from "@/components/site/Layout";
import Home from "@/pages/Home";
// Slug-only lists (auto-generated by scripts/generateRouteSlugs.js as a
// prebuild step) so route generation below doesn't pull the full ~1.5 MB of
// landing-page/guide copy into the eager main bundle — LandingPage and
// BlogPostPage each import their own full content lazily, on demand.
import { LANDING_PAGE_SLUGS } from "@/lib/landingPageSlugs";
import { GUIDE_SLUGS } from "@/lib/guideSlugs";
import ChatWidget from "@/components/ChatWidget";

// Route-level code splitting: every page below Home is fetched on demand
// instead of being bundled into the single main.js every route used to ship
// (2.7 MB uncompressed before this change). Prerendered HTML already gives
// crawlers and first paint real content regardless of chunk load timing
// (see scripts/prerender.js), so a brief Suspense fallback here is a safe
// tradeoff, not a content-visibility regression.
const FleetPage = lazy(() => import("@/pages/FleetPage"));
const ServicesPage = lazy(() => import("@/pages/ServicesPage"));
const ServiceDetail = lazy(() => import("@/components/site/ServiceDetail"));
const ServiceAreasPage = lazy(() => import("@/pages/ServiceAreasPage"));
const AboutPage = lazy(() => import("@/pages/AboutPage"));
const ContactPage = lazy(() => import("@/pages/ContactPage"));
const BookingPage = lazy(() => import("@/pages/BookingPage"));
const ReviewsPage = lazy(() => import("@/pages/ReviewsPage"));
const FaqPage = lazy(() => import("@/pages/FaqPage"));
const BlogPage = lazy(() => import("@/pages/BlogPage"));
const BlogPostPage = lazy(() => import("@/pages/BlogPostPage"));
const GalleryPage = lazy(() => import("@/pages/GalleryPage"));
const CityPage = lazy(() => import("@/pages/CityPage"));
const PrivacyPolicyPage = lazy(() => import("@/pages/PrivacyPolicyPage"));
const TermsConditionsPage = lazy(() => import("@/pages/TermsConditionsPage"));
const PoliciesPage = lazy(() => import("@/pages/PoliciesPage"));
const CoveragePage = lazy(() => import("@/pages/CoveragePage"));
const CarSeatServicePage = lazy(() => import("@/pages/CarSeatServicePage"));
const LandingPage = lazy(() => import("@/components/site/LandingPage"));
const EventRoute = lazy(() => import("@/pages/EventRoute"));
const PressPage = lazy(() => import("@/pages/PressPage"));
const PartnersPage = lazy(() => import("@/pages/PartnersPage"));
const Admin = lazy(() => import("@/pages/Admin"));
const CardPage = lazy(() => import("@/pages/CardPage"));

// The digital business card at /card is a standalone page — no chat bubble.
function RoutedChatWidget() {
  const location = useLocation();
  if (location.pathname === "/card") return null;
  return <ChatWidget />;
}

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Suspense fallback={null}>
        <Routes>
          <Route element={<Layout />}>
            <Route path="/" element={<Home />} />
            <Route path="/fleet" element={<FleetPage />} />
            <Route path="/services" element={<ServicesPage />} />
            <Route path="/airport-transportation" element={<ServiceDetail slug="airport-transportation" />} />
            <Route path="/corporate-transportation" element={<ServiceDetail slug="corporate-transportation" />} />
            <Route path="/hourly-chauffeur" element={<ServiceDetail slug="hourly-chauffeur" />} />
            <Route path="/wedding-transportation" element={<ServiceDetail slug="wedding-transportation" />} />
            <Route path="/wine-tours" element={<ServiceDetail slug="wine-tours" />} />
            <Route path="/birthday-celebrations" element={<ServiceDetail slug="birthday-celebrations" />} />
            <Route path="/anniversary-limo-service" element={<ServiceDetail slug="anniversary-limo-service" />} />
            <Route path="/prom-transportation" element={<ServiceDetail slug="prom-transportation" />} />
            <Route path="/long-distance-transportation" element={<ServiceDetail slug="long-distance-transportation" />} />
            <Route path="/service-areas" element={<ServiceAreasPage />} />
            <Route path="/airport-car-service/:city" element={<CityPage />} />
            <Route path="/about" element={<AboutPage />} />
            <Route path="/reviews" element={<ReviewsPage />} />
            <Route path="/gallery" element={<GalleryPage />} />
            <Route path="/faq" element={<FaqPage />} />
            <Route path="/contact" element={<ContactPage />} />
            <Route path="/booking" element={<BookingPage />} />
            <Route path="/privacy-policy" element={<PrivacyPolicyPage />} />
            <Route path="/terms-conditions" element={<TermsConditionsPage />} />
            <Route path="/policies" element={<PoliciesPage />} />
            <Route path="/coverage" element={<CoveragePage />} />
            <Route path="/car-seat-service" element={<CarSeatServicePage />} />
            <Route path="/press" element={<PressPage />} />
            <Route path="/partners" element={<PartnersPage />} />
            <Route path="/blog" element={<BlogPage />} />
            {GUIDE_SLUGS.map((slug) => (
              <Route key={slug} path={`/${slug}`} element={<BlogPostPage slug={slug} />} />
            ))}
            <Route path="/blog/:slug" element={<BlogPostPage />} />
            {LANDING_PAGE_SLUGS.map((slug) => (
              <Route key={slug} path={`/${slug}`} element={<LandingPage slug={slug} />} />
            ))}
          </Route>
          <Route element={<Layout />}>
            <Route path="/:slug" element={<EventRoute />} />
          </Route>
          <Route path="/card" element={<CardPage />} />
          <Route path="/admin" element={<Admin />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
        </Suspense>
        <RoutedChatWidget />
      </BrowserRouter>
      <Toaster position="top-right" richColors />
    </div>
  );
}

export default App;
