// AUTO-GENERATED by scripts/generateRouteSlugs.js (runs as a prebuild/prestart step).
// Do not hand-edit — it is overwritten on every build. Slugs only, no page
// content, so App.js can build its <Route> list without pulling the full
// (large) content objects into the eager main bundle.
export const BLOG_POST_TITLES = [
  {
    "slug": "bwi-airport-car-service-guide-2026",
    "title": "Complete BWI Airport Car Service Guide 2026"
  },
  {
    "slug": "limo-service-vs-uber-maryland",
    "title": "Limo Service vs Uber in Maryland: Which is Better?"
  },
  {
    "slug": "corporate-travel-guide-maryland",
    "title": "Corporate Travel Guide for Maryland Business Executives"
  },
  {
    "slug": "wedding-limo-service-maryland",
    "title": "How to Choose a Wedding Limo Service in Maryland"
  },
  {
    "slug": "airport-transfer-tips-maryland",
    "title": "10 Tips for a Smooth Airport Transfer in Maryland"
  },
  {
    "slug": "how-much-does-limo-service-cost-maryland",
    "title": "Maryland Limo Pricing Guide: 2026 Costs Explained"
  },
  {
    "slug": "airport-limo-vs-uber-maryland",
    "title": "Airport Limo vs Uber in Maryland: Which Should You Choose?"
  },
  {
    "slug": "bwi-airport-car-service-guide",
    "title": "Complete BWI Airport Car Service Guide for Maryland Travelers"
  },
  {
    "slug": "limo-service-for-weddings-maryland",
    "title": "Everything You Need to Know About Wedding Limo Service in Maryland"
  },
  {
    "slug": "best-limo-service-laurel-md",
    "title": "Best Limo Service in Laurel MD: What to Look For"
  },
  {
    "slug": "how-much-does-a-limo-cost-in-maryland",
    "title": "How Much Does a Limo Cost in Maryland? What Actually Sets the Price"
  },
  {
    "slug": "party-bus-vs-stretch-limo-vs-sprinter",
    "title": "Party Bus vs. Stretch Limo vs. Sprinter: Choosing for a Maryland Group Night Out"
  },
  {
    "slug": "black-car-service-vs-town-car-vs-limo",
    "title": "Black Car Service vs. Town Car vs. Limo: What the Terms Actually Mean"
  },
  {
    "slug": "maryland-wedding-limo-planning-timeline",
    "title": "Maryland Wedding Limo Planning Timeline: From Booking to the Getaway Car"
  },
  {
    "slug": "bwi-airport-limousine-for-special-occasions",
    "title": "When to Book an Actual Limousine for BWI Airport Travel"
  },
  {
    "slug": "best-time-to-book-airport-car-service",
    "title": "Best Time to Book Airport Car Service (So You're Never Scrambling)"
  },
  {
    "slug": "airport-limo-vs-uber-real-cost-breakdown",
    "title": "Airport Limo vs. Uber: The Real Cost Breakdown for BWI, DCA & IAD Trips"
  },
  {
    "slug": "wedding-limo-cost-maryland",
    "title": "How Much Does Wedding Limo Service Cost in Maryland?"
  },
  {
    "slug": "corporate-car-service-washington-dc",
    "title": "Corporate Car Service in Washington DC: What Executives Need to Know"
  },
  {
    "slug": "airport-shuttle-vs-private-limo",
    "title": "Airport Shuttle vs. Private Limo: Which Should You Book?"
  },
  {
    "slug": "how-to-book-a-luxury-chauffeur",
    "title": "How to Book a Luxury Chauffeur, Step by Step"
  },
  {
    "slug": "best-limo-service-for-group-travel",
    "title": "How to Choose the Best Limo Service for Group Travel"
  },
  {
    "slug": "airport-transfer-tips-frequent-travelers",
    "title": "10 Airport Transfer Tips Frequent Travelers Swear By"
  },
  {
    "slug": "black-car-service-vs-traditional-taxi",
    "title": "Black Car Service vs. Traditional Taxi: What's Actually Different?"
  },
  {
    "slug": "limo-service-in-maryland-complete-guide",
    "title": "How to Choose a Limo Service in Maryland: A Complete Buyer's Guide"
  },
  {
    "slug": "corporate-sedan-service-guide",
    "title": "Corporate Sedan Service: What Business Travelers Should Expect"
  },
  {
    "slug": "bwi-airport-limo-pricing-explained",
    "title": "BWI Airport Limo Pricing: What You're Actually Paying For"
  },
  {
    "slug": "event-limo-service-guide",
    "title": "Event Limo Service: Which Occasions Actually Call for One"
  },
  {
    "slug": "baltimore-ravens-game-day-limo",
    "title": "Baltimore Ravens Game Day: Skip the M&T Bank Stadium Parking Nightmare"
  },
  {
    "slug": "concert-transportation-baltimore",
    "title": "Concert Transportation in Baltimore: CFG Bank Arena, Merriweather & Beyond"
  },
  {
    "slug": "luxury-car-service-dc-beyond-business",
    "title": "Luxury Car Service in DC Isn't Just for Business Travelers"
  },
  {
    "slug": "airport-transfer-tips-first-time-travelers",
    "title": "Airport Transfer Tips for First-Time Travelers (No Experience Needed)"
  },
  {
    "slug": "merriweather-post-pavilion-concert-transportation",
    "title": "Merriweather Post Pavilion Concert Transportation Guide"
  },
  {
    "slug": "maryland-live-casino-night-out-car-service",
    "title": "Maryland Live! Casino Night-Out Car Service Guide"
  },
  {
    "slug": "six-flags-america-group-outing-transportation",
    "title": "Six Flags America Group Outing Transportation Guide"
  },
  {
    "slug": "milestone-birthday-party-transportation-laurel-columbia",
    "title": "Milestone Birthday Party Transportation in Laurel & Columbia, MD"
  },
  {
    "slug": "private-chauffeur-day-annapolis-ellicott-city",
    "title": "A Private Chauffeur Day: Annapolis & Historic Ellicott City Touring"
  },
  {
    "slug": "prom-limo-service-maryland-parents-guide",
    "title": "Prom Limo Service in Maryland: A Parent's Planning Guide"
  },
  {
    "slug": "bachelor-bachelorette-party-transportation-maryland",
    "title": "Bachelor & Bachelorette Party Transportation in Maryland"
  },
  {
    "slug": "how-many-cars-wedding-party-maryland",
    "title": "How Many Cars Do You Actually Need for Your Wedding Party?"
  },
  {
    "slug": "coordinating-chauffeur-wedding-vendor-timeline",
    "title": "Coordinating Your Chauffeur With Your Wedding Vendor Timeline"
  },
  {
    "slug": "proposal-anniversary-chauffeur-maryland",
    "title": "Proposal & Anniversary Chauffeur Experiences in Maryland"
  },
  {
    "slug": "hourly-as-directed-chauffeur-corporate-roadshows",
    "title": "Hourly As-Directed Chauffeur Service for Corporate Roadshows"
  },
  {
    "slug": "corporate-holiday-party-transportation-planning-guide",
    "title": "Corporate Holiday Party Transportation: A Planning Guide for Office Managers"
  },
  {
    "slug": "sedan-vs-suv-vs-sprinter-which-vehicle",
    "title": "Sedan vs. SUV vs. Sprinter Van: Which Vehicle Should You Actually Book?"
  },
  {
    "slug": "fort-meade-nsa-laurel-corporate-campus-transportation",
    "title": "Fort Meade, NSA & Laurel Corporate Campus Visitor Transportation Guide"
  },
  {
    "slug": "conference-association-meeting-transportation-maryland",
    "title": "Conference & Association Meeting Transportation in Maryland"
  },
  {
    "slug": "bwi-dca-terminal-layouts-2026-pickup-zones",
    "title": "BWI & DCA Terminal Layouts in 2026: Pickup Zones and What Changed"
  },
  {
    "slug": "family-reunion-airport-transportation-sprinter-van",
    "title": "Family Reunion Airport Transportation: Why a Sprinter Van Solves the Group Problem"
  },
  {
    "slug": "winter-weather-flight-delay-playbook-maryland",
    "title": "The Winter Weather & Flight Delay Playbook for Maryland Travelers"
  },
  {
    "slug": "combining-air-travel-marc-train-private-chauffeur",
    "title": "Combining Air Travel and the MARC Train With a Private Chauffeur"
  },
  {
    "slug": "college-graduation-season-transportation-maryland-umd",
    "title": "College Graduation Season Transportation Guide for Maryland Families"
  },
  {
    "slug": "complete-guide-limo-service-maryland",
    "title": "The Complete Guide to Limo Service in Maryland"
  },
  {
    "slug": "top-occasions-marylanders-book-limo-car-service",
    "title": "Top Occasions Marylanders Book a Limo or Car Service For"
  },
  {
    "slug": "areas-we-serve-county-by-county-guide-maryland",
    "title": "Areas We Serve: A County-by-County Guide to Limo Service Across Maryland"
  },
  {
    "slug": "how-corporate-accounts-work-maryland-limousine-service",
    "title": "How Corporate Accounts Work with a Maryland Limousine Service"
  },
  {
    "slug": "why-maryland-families-choose-local-limo-company",
    "title": "Why Maryland Families Choose a Local Limo Company Over National Chains"
  },
  {
    "slug": "limo-service-umd-college-park-students-parents",
    "title": "Limo Service for UMD Families: The College Park Transportation Guide"
  },
  {
    "slug": "rockville-north-bethesda-night-out-car-service",
    "title": "Rockville & North Bethesda Nights Out: A Car Service Guide"
  },
  {
    "slug": "howard-county-columbia-corporate-corridor-transportation",
    "title": "Howard County's Corporate Corridor: A Columbia Business Travel Guide"
  },
  {
    "slug": "anne-arundel-county-wedding-venue-transportation",
    "title": "Wedding Transportation for Anne Arundel County's Venues"
  },
  {
    "slug": "frederick-county-wine-country-chauffeur-service",
    "title": "Frederick County Wine Country by Chauffeur: A Planning Guide"
  },
  {
    "slug": "law-firm-client-transportation-maryland",
    "title": "Client & Visitor Transportation for Maryland Law Firms"
  },
  {
    "slug": "real-estate-closing-showing-transportation-maryland",
    "title": "Car Service for Maryland Real Estate Closings & Showings"
  },
  {
    "slug": "what-limo-service-can-cannot-do-non-emergency-medical-transport",
    "title": "Limo Service & Non-Emergency Medical Transport: What's Actually Possible"
  },
  {
    "slug": "maryland-holiday-lights-touring-chauffeur",
    "title": "Touring Maryland's Holiday Lights by Private Chauffeur"
  },
  {
    "slug": "new-years-eve-car-service-maryland",
    "title": "New Year's Eve Car Service in Maryland: What to Know"
  },
  {
    "slug": "college-move-in-day-transportation-maryland",
    "title": "College Move-In Day Transportation for Maryland Families"
  },
  {
    "slug": "limo-service-vs-renting-a-car-maryland-weekend",
    "title": "Limo Service or a Rental Car for Your Maryland Weekend?"
  },
  {
    "slug": "how-to-read-a-maryland-limo-service-contract",
    "title": "How to Read a Maryland Limo Service Contract Before You Sign"
  },
  {
    "slug": "what-maryland-psc-carrier-licensing-means-for-consumers",
    "title": "What Maryland PSC Carrier Licensing Actually Means for You"
  },
  {
    "slug": "limo-service-deposit-cancellation-policies-explained",
    "title": "Limo Service Deposits & Cancellation Policies, Explained"
  },
  {
    "slug": "off-peak-vs-peak-pricing-maryland-limo-service",
    "title": "Off-Peak vs. Peak Pricing: When Maryland Limo Service Costs Less"
  },
  {
    "slug": "multicultural-wedding-transportation-logistics-maryland",
    "title": "Planning Transportation for a Multicultural Wedding in Maryland"
  },
  {
    "slug": "barn-farm-venue-wedding-transportation-maryland",
    "title": "Getting a Limo to a Maryland Barn or Farm Wedding Venue"
  },
  {
    "slug": "rehearsal-dinner-brunch-transportation-maryland",
    "title": "Transportation for the Rehearsal Dinner and Next-Day Brunch"
  },
  {
    "slug": "brewery-winery-tour-party-bus-maryland",
    "title": "Brewery & Winery Tour Party Buses in Maryland: A Planning Guide"
  },
  {
    "slug": "quinceanera-sweet-16-limousine-maryland",
    "title": "The Maryland & DC Quinceañera and Sweet 16 Limousine Guide"
  },
  {
    "slug": "bar-bat-mitzvah-transportation-maryland",
    "title": "Bar & Bat Mitzvah Transportation Planning Guide for Maryland & DC"
  },
  {
    "slug": "funeral-memorial-limousine-etiquette-guide",
    "title": "Funeral & Memorial Limousine Service: A Practical Etiquette Guide"
  },
  {
    "slug": "bridal-baby-shower-group-transportation-maryland",
    "title": "Bridal & Baby Shower Group Transportation Guide for Maryland & DC"
  },
  {
    "slug": "golf-outing-country-club-chauffeur-maryland",
    "title": "Golf Outing & Country Club Chauffeur Service in Maryland & DC"
  },
  {
    "slug": "ski-weekend-chauffeur-wisp-seven-springs",
    "title": "Ski Weekend Chauffeur Guide: Wisp Resort & Seven Springs From Maryland & DC"
  },
  {
    "slug": "nationals-park-audi-field-dc-sports-transportation",
    "title": "Nationals Park & Audi Field: DC Sports Fan Group Transportation Guide"
  },
  {
    "slug": "loudoun-county-wine-country-chauffeur-tour",
    "title": "Loudoun County & Northern Virginia Wine Country Chauffeur Tour Guide"
  },
  {
    "slug": "corporate-team-offsite-retreat-transportation-guide",
    "title": "Corporate Team Offsite & Retreat Transportation Planning Guide"
  },
  {
    "slug": "nonprofit-gala-black-tie-fundraiser-transportation-dc",
    "title": "Nonprofit Gala & Black-Tie Fundraiser Transportation Guide for DC"
  },
  {
    "slug": "cherry-blossom-season-dc-chauffeur-guide",
    "title": "Cherry Blossom Season in DC: A Chauffeured Visitor's Guide"
  },
  {
    "slug": "thanksgiving-travel-rush-bwi-dca-iad-chauffeur-guide",
    "title": "Thanksgiving Travel Rush: The BWI, DCA & IAD Chauffeur Guide"
  },
  {
    "slug": "rehoboth-bethany-ocean-city-beach-weekend-chauffeur",
    "title": "Beach Weekend Chauffeur Guide: Rehoboth, Bethany & Ocean City"
  },
  {
    "slug": "debutante-ball-cotillion-transportation-guide",
    "title": "Debutante Ball & Cotillion Transportation Guide for Maryland & DC"
  },
  {
    "slug": "newborn-homecoming-hospital-to-home-car-seat-guide",
    "title": "Newborn Homecoming: The Hospital-to-Home Car Seat Chauffeur Guide"
  },
  {
    "slug": "pet-friendly-luxury-transportation-guide",
    "title": "Pet-Friendly Luxury Transportation Guide for Maryland & DC"
  },
  {
    "slug": "vip-suite-private-box-corporate-client-entertainment",
    "title": "VIP Suite & Private Box Corporate Client Entertainment Transportation Guide"
  },
  {
    "slug": "spa-day-girls-guys-day-out-chauffeur-guide",
    "title": "Spa Day & Girls'/Guys' Day Out Chauffeur Guide for Maryland & DC"
  },
  {
    "slug": "multi-city-business-trip-baltimore-dc-philadelphia",
    "title": "Multi-City Business Trip Guide: Baltimore, DC & Philadelphia in One Day"
  },
  {
    "slug": "military-homecoming-deployment-airport-pickup-guide",
    "title": "Military Homecoming: A Deployment Return Airport Pickup Guide"
  }
];
