// AUTO-GENERATED — do not hand-edit. Regenerated by scripts/generateBlogs.js
// from scripts/generatedBlogPosts.json every time the daily automation runs.
// Same shape as BLOG_POSTS (see blogPosts.js header comment). Merged into
// BLOG_POSTS at the bottom of blogPosts.js.
export const GENERATED_BLOG_POSTS = [];
