// AUTO-GENERATED by scripts/generateRouteSlugs.js (runs as a prebuild/prestart step).
// Do not hand-edit — it is overwritten on every build. Slugs only, no page
// content, so App.js can build its <Route> list without pulling the full
// (large) content objects into the eager main bundle.
export const GUIDE_TITLES = [
  {
    "slug": "uber-vs-limo-service-bwi",
    "title": "Uber vs. Limo Service to BWI Airport: An Honest Side-by-Side"
  },
  {
    "slug": "why-not-take-uber-to-bwi-airport",
    "title": "Why Not Just Take an Uber to BWI? Six Scenarios Worth Planning For"
  },
  {
    "slug": "bwi-airport-transportation-guide",
    "title": "BWI Airport Transportation Guide: Every Way to Get There and Back"
  },
  {
    "slug": "corporate-car-service-vs-uber-dc",
    "title": "Corporate Car Service vs. Uber in Washington DC: A Guide for Travel Managers"
  },
  {
    "slug": "laurel-md-transportation-guide",
    "title": "Laurel, MD Transportation Guide: Highways, MARC, Buses and Airport Access"
  },
  {
    "slug": "columbia-md-transportation-guide",
    "title": "Columbia, MD Transportation Guide: Roads, Buses, Concert Nights and Airports"
  },
  {
    "slug": "annapolis-md-transportation-guide",
    "title": "Annapolis, MD Transportation Guide: Roads, Parking, Big Events and Airports"
  },
  {
    "slug": "wedding-transportation-guide-maryland-dc-virginia",
    "title": "The Complete Wedding Transportation Guide for Maryland, DC & Virginia Couples"
  },
  {
    "slug": "holiday-lights-limo-tours-maryland-dc-virginia",
    "title": "Holiday Lights Limo & Chauffeur Tours: The Complete Guide for Maryland, DC & Northern Virginia"
  }
];
