// AUTO-GENERATED by scripts/generateRouteSlugs.js (runs as a prebuild/prestart step).
// Do not hand-edit — it is overwritten on every build. Slugs only, no page
// content, so App.js can build its <Route> list without pulling the full
// (large) content objects into the eager main bundle.
export const GUIDE_SLUGS = [
  "uber-vs-limo-service-bwi",
  "why-not-take-uber-to-bwi-airport",
  "bwi-airport-transportation-guide",
  "corporate-car-service-vs-uber-dc",
  "laurel-md-transportation-guide",
  "columbia-md-transportation-guide",
  "annapolis-md-transportation-guide",
  "wedding-transportation-guide-maryland-dc-virginia"
];
