import { IMAGES } from "@/lib/data";

// Vehicle label sets (must match `${category} — ${name}` from FLEET).
const SEDAN_TRIO = [
  "Business Sedan — Mercedes E-Class",
  "First Class Sedan — BMW 7 Series",
  "Premium SUV — Cadillac Escalade",
];
const GROUP_TRIO = [
  "Luxury SUV — Chevrolet Suburban",
  "Premium SUV — Cadillac Escalade",
  "Sprinter Executive — Mercedes Sprinter",
];
const BEACH_TRIO = [
  "Premium SUV — Cadillac Escalade",
  "Luxury SUV — Chevrolet Suburban",
  "Sprinter Shuttle — Mercedes Sprinter",
];

export const LANDING_PAGES = {
  // ---------------------------------------------------------------- CRUISE
  "cruise-transfers": {
    metaTitle: "Baltimore Cruise Port Transfers | 92 Limo Service",
    metaDescription:
      "Luxury chauffeur transfers to the Port of Baltimore cruise terminal from BWI, DC, MD & VA. Flight-to-port timing, luggage help, and Sprinter vans. 24/7.",
    eyebrow: "CRUISE TRANSFERS",
    h1: "Baltimore Cruise Port Transfers",
    subtitle:
      "Stress-free, on-time chauffeured transfers to and from the Port of Baltimore Cruise Terminal — from BWI, DC, Maryland, and Virginia.",
    image: IMAGES.airportPickup,
    alt: "Luxury chauffeur loading luggage for a Baltimore cruise port transfer",
    highlightsHeading: "Why Book Your Cruise Transfer With 92 Limo Service",
    intro: [
      "Starting your cruise should feel like the beginning of a vacation — not a logistics headache. 92 Limo Service provides luxury chauffeured transfers to and from the Port of Baltimore Cruise Terminal at South Locust Point, the embarkation point for Carnival, Royal Caribbean, and seasonal sailings up and down the East Coast. Whether you are coming from your front door in Maryland, a downtown DC hotel, Northern Virginia, or flying into BWI Marshall the day of your sailing, we make sure you arrive relaxed, on schedule, and ready to step aboard.",
      "Pre-cruise pickups are planned around your boarding window, not ours. Your chauffeur arrives early, helps load every bag, and drives you directly to the terminal drop-off so you can hand off your luggage to the porters and walk straight to check-in. There is no circling for parking, no shuttle waiting, and no worrying about long-term parking fees that add up over a week at sea. For travelers flying in, we coordinate flight-to-port timing — tracking your inbound flight and adjusting pickup automatically so a delay never costs you your cruise.",
      "Post-cruise returns are just as smooth. Disembarkation mornings are notoriously chaotic, so we monitor the port and stage your vehicle for a prompt, comfortable pickup the moment you clear the terminal. After a week away, the last thing you want is to hunt for a ride home — your chauffeur is already there, climate-controlled cabin ready, bottled water on hand, and a direct route home or back to the airport.",
      "Traveling with extended family, a group of friends, or a corporate retreat? Our Mercedes Sprinter vans seat large parties together with dedicated luggage space, so nobody is splitting across multiple cars or paying surge rates on a rideshare app. From a couple in a Business Sedan to a multi-generational family in a Sprinter van, we right-size the vehicle to your group and your bags — and quote a flat, all-inclusive rate up front.",
    ],
    highlights: [
      { title: "Direct Port-of-Baltimore Service", desc: "Door-to-terminal transfers to South Locust Point Cruise Terminal — no parking, no shuttles, no stress." },
      { title: "Flight-to-Port Coordination", desc: "Flying in to sail? We track your flight and time your pickup so a delay never threatens your departure." },
      { title: "Full Luggage Handling", desc: "Your chauffeur loads and unloads every bag and helps you to the porters at the terminal entrance." },
      { title: "Post-Cruise Pickups", desc: "We stage your vehicle for disembarkation morning so you ride home the moment you clear the terminal." },
      { title: "Group & Family Options", desc: "Sprinter vans and SUVs keep your whole party — and all the luggage — together in one comfortable vehicle." },
      { title: "Flat, All-Inclusive Pricing", desc: "Transparent quotes covering tolls, taxes, and gratuity. No surge pricing, no surprises." },
    ],
    vehicles: GROUP_TRIO,
    faqs: [
      { q: "Which cruise terminal do you serve?", a: "We serve the Port of Baltimore Cruise Terminal at South Locust Point, the embarkation point for Carnival, Royal Caribbean, and other lines sailing from Baltimore." },
      { q: "Can you pick me up from BWI and take me straight to the cruise port?", a: "Yes. We provide direct flight-to-port transfers from BWI Marshall Airport. We track your inbound flight and time your pickup so you arrive at the terminal with comfortable margin before boarding closes." },
      { q: "Do you help with luggage?", a: "Absolutely. Your chauffeur loads and unloads all of your bags and assists you to the curbside porters at the terminal — and helps again on your return." },
      { q: "Can you accommodate large groups going on the same cruise?", a: "Yes. Our Mercedes Sprinter vans and full-size SUVs comfortably seat larger parties with dedicated luggage space, keeping your whole group together in one vehicle." },
      { q: "How far in advance should I book a cruise transfer?", a: "We recommend booking at least a few days ahead, and earlier during peak cruise season, to guarantee your preferred vehicle. Call 877-679-0100 anytime, 24/7." },
      { q: "What does the price include?", a: "Our cruise transfers are quoted as flat, all-inclusive rates covering base fare, tolls, taxes, and standard gratuity — with no surge pricing." },
    ],
    ctaTitle: "Ready to Set Sail?",
    ctaSubtitle: "Reserve your Baltimore cruise port transfer — we confirm every booking with an all-inclusive quote.",
  },

  // ---------------------------------------------------------------- SPORTS
  "sports-events": {
    metaTitle: "Ravens & Orioles Game Transportation | 92 Limo Service",
    metaDescription:
      "Chauffeured game-day rides to M&T Bank Stadium (Ravens) and Camden Yards (Orioles). No parking, tailgate drop-offs, group vans, and safe rides home.",
    eyebrow: "SPORTS & EVENTS",
    h1: "Ravens & Orioles Game Transportation",
    subtitle:
      "Skip the parking and the traffic. Arrive at M&T Bank Stadium and Camden Yards in style — and get home safely after the final out.",
    image: IMAGES.suv,
    alt: "Black luxury SUV providing game-day transportation in Baltimore",
    highlightsHeading: "Game Day, Done Right",
    intro: [
      "Game day in Baltimore is electric — and a whole lot more enjoyable when you are not fighting for a parking spot or worrying about the drive home. 92 Limo Service provides chauffeured transportation to every Ravens home game at M&T Bank Stadium and every Orioles game at Oriole Park at Camden Yards, two of the best venues in professional sports, conveniently located side by side in downtown Baltimore. We pick you up at home, the office, or your hotel and drop you right at the gate.",
      "For tailgaters, we time drop-offs around the lots so you have plenty of time to fire up the grill before kickoff — and we will be back at your pickup point when the game ends, no walking through dark parking lots or waiting on a surge-priced rideshare. Because you are not driving, everyone in your group can relax and enjoy the day exactly the way game day is meant to be enjoyed.",
      "Rolling with a crew? Our Mercedes Sprinter vans and full-size SUVs keep groups of friends, families, and coworkers together in one vehicle, with room for coolers, gear, and team flags. Corporate clients and suite holders rely on us for polished, on-time arrivals when entertaining clients — we will coordinate multiple pickups, handle the downtown logistics, and present the professional image your business expects.",
      "Beyond Ravens and Orioles games, we provide the same reliable, luxurious service for concerts, championship events, and big nights out across the region — from CFG Bank Arena downtown to stadium shows and everything in between. One trusted chauffeur partner, every event on your calendar, with flat all-inclusive pricing and a safe ride home every time.",
    ],
    highlights: [
      { title: "Drop-Off at the Gate", desc: "Arrive right at M&T Bank Stadium or Camden Yards — no parking lots, no long walks, no hassle." },
      { title: "Tailgate-Friendly Timing", desc: "We schedule drop-offs around the lots so you have time to tailgate before kickoff or first pitch." },
      { title: "Safe Rides Home", desc: "Enjoy the game and a few drinks — your chauffeur handles the drive home, every time." },
      { title: "Group Transport", desc: "Sprinter vans and SUVs keep your whole crew together, with room for coolers and gear." },
      { title: "Corporate & Suite Service", desc: "Polished, punctual arrivals for client entertaining, suite nights, and company outings." },
      { title: "Concerts & Big Events Too", desc: "The same first-class service for shows, championships, and nights out across the DMV." },
    ],
    vehicles: GROUP_TRIO,
    faqs: [
      { q: "Do you provide transportation to both Ravens and Orioles games?", a: "Yes — we serve every Ravens home game at M&T Bank Stadium and every Orioles game at Oriole Park at Camden Yards, plus concerts and other major events in Baltimore and across the DMV." },
      { q: "Can you drop us off for tailgating?", a: "Absolutely. We time your drop-off around the tailgate lots and stadium gates, and we return to your designated pickup point after the game." },
      { q: "How does pickup work after the game?", a: "We coordinate a specific post-game pickup location and time. Because crowds and traffic are heavy, your chauffeur stages nearby and brings the vehicle to you so you are not waiting in the crowd." },
      { q: "Can you handle a large group?", a: "Yes. Our Sprinter vans and full-size SUVs keep groups together in a single vehicle with space for coolers and gear — far more comfortable and cost-effective than multiple rideshares." },
      { q: "Do you work with corporate and suite clients?", a: "We do. We provide professional, on-time service for client entertaining and suite nights, including coordinated multi-stop pickups. Ask about recurring corporate accounts." },
      { q: "Is pricing flat or metered?", a: "We quote flat, all-inclusive game-day rates covering tolls, taxes, and gratuity — with no surge pricing even on the busiest nights." },
    ],
    ctaTitle: "Make Game Day Effortless",
    ctaSubtitle: "Book your chauffeur to the next Ravens or Orioles game and skip the parking entirely.",
  },

  // ---------------------------------------------------------------- ROUTES
  "bwi-to-washington-dc": {
    metaTitle: "BWI Airport to Washington DC Car Service | 92 Limo Service",
    metaDescription:
      "Private car service from BWI Airport to Washington DC. Meet & greet, flight tracking, flat-rate pricing, and 24/7 chauffeurs to DC hotels & offices.",
    eyebrow: "BWI → WASHINGTON DC",
    h1: "BWI Airport to Washington DC Car Service",
    subtitle: "Private, chauffeured transfers between BWI Marshall and the nation's capital — roughly 32 miles of effortless luxury.",
    image: IMAGES.dcSkyline,
    alt: "Washington DC skyline — BWI to DC luxury car service",
    highlightsHeading: "The Premier BWI–DC Transfer",
    intro: [
      "The 32-mile trip between BWI Marshall Airport and Washington, D.C. should be the easy part of your journey — and with 92 Limo Service, it is. Our chauffeurs meet you at baggage claim with a name sign, carry your bags, and have you settled into a spotless luxury vehicle within minutes of landing. Whether you are headed to a Capitol Hill hotel, a K Street office, a Georgetown townhouse, or a conference at the convention center, you ride in quiet comfort while we handle the Beltway and downtown traffic.",
      "Travel time between BWI and downtown DC typically runs 45 to 60 minutes depending on the time of day, and our chauffeurs know every alternate route when the BW Parkway or I-95 slows down. We track your inbound flight in real time, so an early arrival or a delay simply means we adjust — your car is ready when you are, with no extra charge for reasonable schedule changes.",
      "Business travelers appreciate the professionalism: clean vehicles, discreet chauffeurs, USB charging, and the ability to take calls or prep for a meeting on the move. Families and leisure travelers love arriving at the monuments and museums relaxed rather than wrestling luggage on a train. Either way, you get a flat, all-inclusive rate quoted in advance — no metering, no surge pricing, no surprises.",
      "From the Mercedes-Benz E-Class for solo and business trips to the Cadillac Escalade and Sprinter vans for groups and extra luggage, we match the vehicle to your needs. And because we run 24/7, your red-eye arrival or pre-dawn departure to Reagan, Dulles, or back to BWI is covered with the same reliability.",
      "Beyond the airport run, many DC clients keep us on call for their entire visit — meetings across the District, dinner reservations in Georgetown, evening events on Capitol Hill, and the return trip to the airport. With one trusted chauffeur partner handling every leg, there are no rideshare surprises, no surge pricing during rush hour or rain, and no waiting on a curb. We serve every DC hotel, embassy, and office building, and we are happy to set up recurring corporate accounts for teams who travel between Maryland and the capital regularly.",
    ],
    highlights: [
      { title: "Meet & Greet at BWI", desc: "Your chauffeur greets you inside the terminal with a name sign and helps with luggage." },
      { title: "Real-Time Flight Tracking", desc: "We monitor your flight and adjust pickup for early arrivals or delays at no extra charge." },
      { title: "Flat, All-Inclusive Rate", desc: "One transparent price covering tolls, taxes, and gratuity — quoted before you ride." },
      { title: "Door-to-Door in DC", desc: "Direct service to hotels, offices, monuments, and residences throughout Washington, D.C." },
      { title: "24/7 Availability", desc: "Red-eye arrivals and pre-dawn departures are no problem — we run around the clock." },
      { title: "Business-Ready Comfort", desc: "Quiet cabins, USB charging, and discreet chauffeurs so you can work or relax en route." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How long does the BWI to Washington DC drive take?", a: "Typically 45 to 60 minutes depending on traffic and your exact DC destination. The distance is roughly 32 miles via I-95 or the Baltimore-Washington Parkway." },
      { q: "Will my chauffeur meet me inside the terminal?", a: "Yes. We offer meet & greet service — your chauffeur waits at baggage claim with a name sign and assists with your luggage. Curbside pickup is also available if you prefer." },
      { q: "What if my flight is delayed?", a: "We track your flight in real time and adjust your pickup automatically. There is no extra charge for reasonable delays." },
      { q: "Is the price fixed?", a: "Yes. We quote a flat, all-inclusive rate for BWI–DC transfers covering tolls, taxes, and gratuity. There is no metering and no surge pricing." },
      { q: "Can you accommodate groups or extra luggage?", a: "Definitely. Choose a full-size SUV or a Mercedes Sprinter van for larger parties and additional bags." },
      { q: "Do you serve all of Washington DC?", a: "Yes — we provide door-to-door service to every DC neighborhood, hotel, office, and venue, as well as Reagan National (DCA) and Dulles (IAD)." },
    ],
    ctaTitle: "Book Your BWI–DC Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Washington, D.C. with flat, all-inclusive pricing.",
  },

  "bwi-to-annapolis": {
    metaTitle: "BWI Airport to Annapolis Car Service | 92 Limo Service",
    metaDescription:
      "Luxury car service from BWI Airport to Annapolis, MD. Flight tracking, meet & greet, and flat-rate transfers to the Naval Academy, City Dock & hotels.",
    eyebrow: "BWI → ANNAPOLIS",
    h1: "BWI Airport to Annapolis Car Service",
    subtitle: "Quick, comfortable chauffeured transfers between BWI Marshall and Maryland's historic capital — about 25 miles.",
    image: IMAGES.sedan,
    alt: "Luxury sedan for BWI to Annapolis car service",
    highlightsHeading: "Sailing-Capital Comfort",
    intro: [
      "Annapolis is one of the most charming destinations in Maryland — home to the United States Naval Academy, the historic City Dock, and a waterfront downtown that draws sailors, families, and business travelers alike. 92 Limo Service makes the roughly 25-mile trip from BWI Marshall Airport to Annapolis effortless, with professional chauffeurs, immaculate vehicles, and flat-rate pricing you can count on.",
      "The drive typically takes 25 to 35 minutes via I-97 and US-50, and our chauffeurs know the quickest path to the Naval Academy gates, the downtown hotels along Compromise and Main Street, the Annapolis Town Center, and the residential neighborhoods of Eastport and beyond. We meet you at baggage claim, handle your luggage, and have you on the road in minutes.",
      "Whether you are arriving for a Naval Academy event such as Commissioning Week or a parents' weekend, a sailing trip, a waterfront wedding, or a corporate meeting, you will appreciate arriving relaxed and on time. We track your inbound flight, adjust automatically for delays, and quote one transparent, all-inclusive price — no metering and no surge.",
      "From the Mercedes-Benz E-Class for individuals and couples to SUVs and Sprinter vans for families and groups with luggage, we match the right vehicle to your trip. And with 24/7 availability, your early-morning departure back to BWI is just as dependable as your arrival.",
      "Because Annapolis fills up fast during Naval Academy events, boat shows, and summer weekends, we recommend reserving early so your preferred vehicle is guaranteed. Our chauffeurs know the one-way streets and limited parking around the historic district and City Dock, and drop you as close to your destination as local access allows. Whether you are a parent visiting a midshipman, a couple in town for a waterfront dinner, or a group heading out on the bay, we make the arrival as smooth and memorable as the stay itself.",
    ],
    highlights: [
      { title: "Naval Academy & City Dock", desc: "Direct service to USNA gates, downtown hotels, City Dock, and Eastport." },
      { title: "Meet & Greet at BWI", desc: "Greeted at baggage claim with a name sign and full luggage assistance." },
      { title: "Flight Tracking", desc: "We watch your flight and adjust pickup for early arrivals or delays automatically." },
      { title: "Flat-Rate Pricing", desc: "One all-inclusive price covering tolls, taxes, and gratuity — no surprises." },
      { title: "Events & Weddings", desc: "Reliable transport for Commissioning Week, parents' weekends, and waterfront weddings." },
      { title: "24/7 Service", desc: "Around-the-clock chauffeurs for early departures and late arrivals." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is Annapolis from BWI Airport?", a: "About 25 miles, typically a 25 to 35 minute drive via I-97 and US-50 depending on traffic." },
      { q: "Do you serve the Naval Academy?", a: "Yes. We regularly transport families and guests to the USNA for Commissioning Week, parents' weekends, sporting events, and ceremonies, with door-to-door drop-off near the gates." },
      { q: "Can you handle luggage for a sailing trip or longer stay?", a: "Of course. Our SUVs and Sprinter vans offer generous luggage capacity for extended trips and gear." },
      { q: "What if my flight arrives early or late?", a: "We track your flight and adjust your pickup time automatically, with no extra charge for reasonable changes." },
      { q: "Is pricing flat or metered?", a: "Flat and all-inclusive — your quote covers the fare, tolls, taxes, and gratuity, with no surge pricing." },
      { q: "Do you offer return trips to the airport?", a: "Yes, we provide round-the-clock return service from Annapolis to BWI, DCA, and IAD." },
      { q: "Can you provide hourly or as-directed service while I'm in Annapolis?", a: "Yes. Beyond the airport transfer, we offer hourly chauffeur service so you can keep a vehicle and driver on hand for a waterfront dinner, a sailing charter, or multiple stops around town and the Naval Academy. It is an easy, flat-rate way to get around historic Annapolis without parking or rideshare hassles." },
    ],
    ctaTitle: "Book Your Annapolis Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Annapolis with flat, all-inclusive pricing.",
  },

  "bwi-to-baltimore": {
    metaTitle: "BWI Airport to Baltimore Car Service | 92 Limo Service",
    metaDescription:
      "Luxury car service from BWI Airport to Baltimore, MD. Meet & greet, flight tracking, and flat-rate transfers to the Inner Harbor, hotels & Johns Hopkins.",
    eyebrow: "BWI → BALTIMORE",
    h1: "BWI Airport to Baltimore Car Service",
    subtitle: "A short, seamless luxury transfer between BWI Marshall and downtown Baltimore — only about 10 miles.",
    image: IMAGES.heroBg,
    alt: "Luxury black car service from BWI to Baltimore",
    highlightsHeading: "Charm City, the Easy Way",
    intro: [
      "At roughly 10 miles, the trip from BWI Marshall Airport to downtown Baltimore is one of the quickest airport transfers in the region — and 92 Limo Service makes it the most comfortable. We meet you at baggage claim, take your bags, and have you gliding toward the Inner Harbor, Harbor East, Fells Point, or your hotel within minutes of landing, usually a 15 to 20 minute drive.",
      "Baltimore draws business travelers to its downtown offices and convention center, patients and families to Johns Hopkins and the University of Maryland Medical Center, and visitors to attractions like the National Aquarium, Camden Yards, and M&T Bank Stadium. Whatever brings you to Charm City, our chauffeurs know the fastest routes and the best drop-off points, so you arrive relaxed and on schedule.",
      "We track your inbound flight and adjust automatically for early arrivals or delays, and we are available 24/7 for red-eye landings and pre-dawn departures. Every trip is quoted as a flat, all-inclusive rate — covering tolls, taxes, and gratuity — so the short distance never comes with a surprise fare.",
      "From a Mercedes-Benz E-Class for solo travelers to SUVs and Sprinter vans for groups, families, and conference teams, we right-size the vehicle to your party and luggage. And because Baltimore is our home turf, we also provide game-day service to Orioles and Ravens games just minutes from the harbor.",
      "Local knowledge matters in Baltimore, where one-way streets, harbor events, and game-day road closures can turn a ten-minute hop into a frustrating crawl for an unfamiliar driver. Our chauffeurs navigate it daily and choose the smartest approach to your hotel, hospital, or venue. Conference attendees, wedding guests, and visiting families all appreciate stepping out of the terminal into a ready vehicle and arriving downtown without ever touching a steering wheel or a parking app.",
    ],
    highlights: [
      { title: "Inner Harbor & Downtown", desc: "Direct drop-off at harbor hotels, Harbor East, Fells Point, and the convention center." },
      { title: "Johns Hopkins & Medical Centers", desc: "Comfortable, reliable transport for patients, families, and medical professionals." },
      { title: "Fast 15–20 Minute Transfer", desc: "Only about 10 miles from BWI — one of the quickest premium transfers around." },
      { title: "Meet & Greet + Flight Tracking", desc: "Greeted at baggage claim; we monitor your flight and adjust for delays." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — no metering or surge." },
      { title: "Game-Day Service", desc: "Easy rides to Orioles and Ravens games minutes from the Inner Harbor." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is downtown Baltimore from BWI?", a: "About 10 miles — typically a 15 to 20 minute drive depending on traffic." },
      { q: "Do you serve Johns Hopkins and the medical campuses?", a: "Yes. We provide comfortable door-to-door transfers to Johns Hopkins, the University of Maryland Medical Center, and other hospitals for patients, families, and staff." },
      { q: "Will you meet me inside the terminal?", a: "Yes — meet & greet at baggage claim with luggage assistance is available, as is curbside pickup if you prefer." },
      { q: "Is the fare fixed for such a short trip?", a: "Yes. Even short transfers are quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Can you take larger groups?", a: "Absolutely — full-size SUVs and Sprinter vans accommodate groups, families, and conference teams with luggage." },
      { q: "Do you offer return service to BWI?", a: "Yes, 24/7, including early-morning departures and late-night arrivals." },
      { q: "Can you handle convention and group arrivals together?", a: "Yes. For conventions at the Baltimore Convention Center and group events, we coordinate multiple vehicles and staggered arrivals so your whole party reaches the hotel or venue smoothly. SUVs and Sprinter vans keep groups together, and we can set up a single billing account for the organizer." },
    ],
    ctaTitle: "Book Your Baltimore Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Baltimore with flat, all-inclusive pricing.",
  },

  "bwi-to-bethesda": {
    metaTitle: "BWI Airport to Bethesda Car Service | 92 Limo Service",
    metaDescription:
      "Private car service from BWI Airport to Bethesda, MD. Flight tracking, meet & greet, and flat-rate transfers to the NIH and downtown Bethesda.",
    eyebrow: "BWI → BETHESDA",
    h1: "BWI Airport to Bethesda Car Service",
    subtitle: "Polished chauffeured transfers between BWI Marshall and Bethesda — about 40 miles of relaxed travel.",
    image: IMAGES.sClassFirst,
    alt: "Mercedes-Benz S-Class for BWI to Bethesda car service",
    highlightsHeading: "Montgomery County's Executive Choice",
    intro: [
      "Bethesda is one of the most affluent and dynamic communities in the DC metro area — home to the National Institutes of Health, Walter Reed National Military Medical Center, a thriving downtown of restaurants and offices, and easy access to the rest of Montgomery County. 92 Limo Service provides luxury chauffeured transfers between BWI Marshall Airport and Bethesda, a trip of roughly 40 miles, with the professionalism that business and medical travelers expect.",
      "Travel time typically runs 50 to 70 minutes depending on traffic on I-495 and the BW Parkway, and our chauffeurs plan around rush-hour congestion to keep you on schedule. We meet you at baggage claim, handle your luggage, and provide a quiet, comfortable cabin where you can take calls, answer email, or simply unwind after a long flight.",
      "Many of our Bethesda clients are visiting the NIH campus, attending medical appointments, or traveling for business with the area's many corporations and consultancies. Others are families and frequent flyers who value a dependable, fixed-rate ride over the uncertainty of rideshare surge pricing. We track your flight, adjust automatically for delays, and quote one transparent, all-inclusive price.",
      "Choose the Mercedes-Benz E-Class or BMW 7 Series for executive travel, or step up to the Cadillac Escalade, Chevrolet Suburban, or a Sprinter van for groups and extra luggage. With 24/7 availability, your early-morning departure back to BWI, Reagan, or Dulles is handled with the same care as your arrival.",
      "Bethesda's blend of medical, federal, and corporate destinations means timing is everything, so our chauffeurs plan around appointment windows, meeting start times, and the area's notorious Beltway congestion. Patients and families visiting the NIH Clinical Center value the calm, comfortable ride; executives value the privacy to take calls; and everyone values knowing the fare in advance. A single call also covers the surrounding Montgomery County communities, from Chevy Chase and Potomac to Rockville and Silver Spring.",
    ],
    highlights: [
      { title: "NIH & Walter Reed", desc: "Reliable transfers to the National Institutes of Health and Walter Reed for appointments and business." },
      { title: "Executive Comfort", desc: "Quiet cabins, USB charging, and discreet chauffeurs ideal for working en route." },
      { title: "Meet & Greet at BWI", desc: "Greeted at baggage claim with a name sign and luggage assistance." },
      { title: "Flight Tracking", desc: "We monitor your flight and adjust for early arrivals or delays automatically." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — never surge-priced." },
      { title: "All of Montgomery County", desc: "Service to Chevy Chase, Rockville, Silver Spring, Potomac, and beyond." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How long is the BWI to Bethesda drive?", a: "Roughly 40 miles, typically 50 to 70 minutes depending on traffic on I-495 and the BW Parkway." },
      { q: "Do you serve the NIH and Walter Reed?", a: "Yes. We regularly transfer clients to the NIH campus and Walter Reed National Military Medical Center, with door-to-door drop-off." },
      { q: "Is this a good option for business travel?", a: "Very much so — our sedans offer quiet, comfortable cabins with charging so you can work or take calls, and our chauffeurs are punctual and discreet." },
      { q: "What if my flight is delayed?", a: "We track your flight and adjust your pickup automatically, with no extra charge for reasonable delays." },
      { q: "Do you also serve nearby Montgomery County towns?", a: "Yes — Chevy Chase, Rockville, Silver Spring, Potomac, and the rest of the county are all within our service area." },
      { q: "Is the price fixed?", a: "Yes, every BWI–Bethesda transfer is quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Can I book recurring rides for medical or business visits?", a: "Absolutely. Many Bethesda clients schedule standing weekly or monthly transfers for treatment at the NIH or recurring business meetings. We keep your preferences on file, assign familiar chauffeurs when possible, and bill to a single account for convenience." },
    ],
    ctaTitle: "Book Your Bethesda Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Bethesda with flat, all-inclusive pricing.",
  },

  "bwi-to-dulles": {
    metaTitle: "BWI to Dulles Airport (IAD) Car Service | 92 Limo Service",
    metaDescription:
      "Airport-to-airport car service between BWI and Washington Dulles (IAD). Reliable, flat-rate transfers for connections and rebookings, 24/7.",
    eyebrow: "BWI → DULLES (IAD)",
    h1: "BWI to Dulles Airport (IAD) Car Service",
    subtitle: "Dependable airport-to-airport transfers between BWI Marshall and Washington Dulles — about 50 miles.",
    image: IMAGES.airportPickup,
    alt: "Chauffeur providing BWI to Dulles airport transfer",
    highlightsHeading: "Airport-to-Airport, Handled",
    intro: [
      "Sometimes the itinerary calls for one airport on the way out and another on the way back — or a connection that is easier by car than by air. 92 Limo Service provides reliable, comfortable airport-to-airport transfers between BWI Marshall Airport and Washington Dulles International (IAD), a trip of roughly 50 miles across the DC metro area.",
      "Travel time between BWI and Dulles generally runs 60 to 90 minutes depending on traffic on I-495 and the Dulles Toll Road, and our chauffeurs build in sensible buffers and monitor conditions so you reach your departure terminal with time to spare. For arriving passengers who need to reach the other airport, we track your inbound flight and stage your vehicle for a prompt pickup.",
      "This route is popular with international travelers connecting through Dulles, business travelers whose outbound and return flights use different airports, and anyone recovering from a missed or rebooked flight who needs a calm, professional ride rather than a scramble. You ride in a spotless luxury vehicle with luggage handled for you, and the fare is a flat, all-inclusive rate quoted in advance.",
      "From the Mercedes-Benz E-Class for solo travelers to SUVs and Sprinter vans for groups with luggage, we match the vehicle to your party. And because we operate 24/7, even the earliest connection or latest rebooking is covered.",
      "We strongly recommend sharing both your arrival and departure times when you book a cross-airport transfer so we can build the right buffer into your pickup. Our chauffeurs monitor real-time conditions on I-495 and the Dulles Toll Road and adjust the route on the fly to protect your connection. For many travelers it is a far more reliable and less stressful option than juggling shuttles or a short connecting flight — and you make the entire trip in a quiet, comfortable cabin with your luggage handled for you.",
    ],
    highlights: [
      { title: "Seamless Airport Connections", desc: "Direct transfers between BWI and IAD terminals for split itineraries and connections." },
      { title: "Flight Tracking", desc: "We monitor your inbound flight and stage your vehicle for a prompt pickup." },
      { title: "Built-In Time Buffers", desc: "Chauffeurs plan around traffic on I-495 and the Dulles Toll Road to keep you on schedule." },
      { title: "Missed-Flight Recovery", desc: "Rebooked onto a flight from the other airport? We get you there calmly and quickly." },
      { title: "Flat, All-Inclusive Rate", desc: "One transparent price covering tolls, taxes, and gratuity — no surge." },
      { title: "24/7 Availability", desc: "Earliest connections and latest rebookings are always covered." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is it from BWI to Dulles?", a: "About 50 miles, typically a 60 to 90 minute drive depending on traffic on I-495 and the Dulles Toll Road." },
      { q: "Can you get me from one airport to the other for a connection?", a: "Yes — airport-to-airport transfers between BWI and IAD are one of our specialties, including same-day connections and rebookings." },
      { q: "What if my arriving flight is delayed?", a: "We track your inbound flight and adjust the pickup automatically so your vehicle is ready when you land." },
      { q: "How much time should I allow between flights?", a: "We recommend allowing generous time given the cross-metro distance. Tell us your departure time and we'll plan a pickup with sensible buffers." },
      { q: "Is the fare fixed?", a: "Yes, BWI–IAD transfers are quoted as a flat, all-inclusive rate covering tolls, taxes, and gratuity." },
      { q: "Do you also serve Reagan National (DCA)?", a: "Yes — we provide transfers among BWI, IAD, and DCA, plus door-to-door service throughout the region." },
      { q: "Can you carry oversized or extra luggage from a long flight?", a: "Yes. Our SUVs and Sprinter vans offer generous cargo room for the extra bags, sports equipment, or instruments that often come with long-haul and international travel, and your chauffeur loads and unloads everything for you." },
    ],
    ctaTitle: "Book Your BWI–Dulles Transfer",
    ctaSubtitle: "Reserve an airport-to-airport chauffeur with flat, all-inclusive pricing.",
  },

  "dca-to-washington-dc": {
    metaTitle: "DCA (Reagan) to Washington DC Car Service | 92 Limo Service",
    metaDescription:
      "Car service from Reagan National (DCA) to Washington DC. Meet & greet, flight tracking, and flat-rate transfers minutes from the terminal, 24/7.",
    eyebrow: "DCA → WASHINGTON DC",
    h1: "DCA (Reagan) to Washington DC Car Service",
    subtitle: "The closest airport to the city — and the smoothest way into it. Chauffeured transfers from Reagan National to DC.",
    image: IMAGES.dcSkyline,
    alt: "Washington DC skyline — DCA to DC car service",
    highlightsHeading: "Closest Airport, Quickest Arrival",
    intro: [
      "Reagan National Airport (DCA) sits just across the Potomac from downtown Washington, making it the most convenient gateway to the capital — and 92 Limo Service turns that short hop into a genuinely first-class arrival. Your chauffeur meets you at baggage claim, handles your luggage, and has you on your way to a DC hotel, office, or residence within minutes, with most downtown destinations only a 10 to 20 minute drive away.",
      "Because DCA is so close to the city, it is the airport of choice for business travelers, government and political visitors, and anyone who values a fast, dignified arrival. We provide quiet, immaculate vehicles where you can take a call, review notes, or simply relax after your flight, with a chauffeur who knows the quickest route to Capitol Hill, downtown, Georgetown, or the convention center.",
      "We track your inbound flight in real time and adjust automatically for early arrivals or delays, and we run 24/7 for the earliest and latest schedules. Every transfer is quoted as a flat, all-inclusive rate — covering tolls, taxes, and gratuity — so there is never a surge or a surprise.",
      "From the Mercedes-Benz E-Class and BMW 7 Series for executives to SUVs and Sprinter vans for groups and luggage, we match the vehicle to your trip — and we also handle transfers between DCA, BWI, and Dulles when your plans call for it.",
      "Reagan National's proximity makes it the favorite of busy professionals, and our service is built for that pace: a chauffeur ready the moment you land, a quick clean exit from the airport, and a direct route to your destination. We also keep many DCA clients for the duration of their visit — point-to-point around the District, evening events, and the short hop back to the terminal — all at transparent flat rates with no surge, even during peak hours or inclement weather.",
    ],
    highlights: [
      { title: "Minutes From Downtown", desc: "Most DC destinations are a 10–20 minute drive from Reagan National." },
      { title: "Meet & Greet at DCA", desc: "Greeted at baggage claim with a name sign and luggage assistance." },
      { title: "Flight Tracking", desc: "We monitor your flight and adjust for early arrivals or delays automatically." },
      { title: "Executive & Government Travel", desc: "Discreet, punctual service trusted by business and political travelers." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — no surge pricing." },
      { title: "24/7 Service", desc: "Around-the-clock chauffeurs for every arrival and departure." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How close is DCA to downtown Washington DC?", a: "Very close — most downtown DC destinations are only a 10 to 20 minute drive from Reagan National Airport." },
      { q: "Will my chauffeur meet me at baggage claim?", a: "Yes. Meet & greet with a name sign and luggage assistance is available, and curbside pickup is offered if you prefer." },
      { q: "Do you handle flight delays?", a: "Yes — we track your flight in real time and adjust your pickup automatically, with no extra charge for reasonable delays." },
      { q: "Is the fare flat?", a: "Yes, every DCA–DC transfer is quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Can you serve groups?", a: "Absolutely — choose a full-size SUV or Sprinter van for larger parties and luggage." },
      { q: "Do you also transfer between airports?", a: "Yes — we provide transfers among DCA, BWI, and IAD, plus door-to-door service across the region." },
      { q: "Do you offer hourly service for meetings around DC?", a: "Yes. After your DCA pickup we can stay with you on an hourly, as-directed basis for back-to-back meetings, client dinners, or events across the District, then return you to the airport — all at a transparent, pre-quoted rate." },
    ],
    ctaTitle: "Book Your DCA–DC Transfer",
    ctaSubtitle: "Reserve a chauffeur from Reagan National into Washington, D.C. with flat-rate pricing.",
  },

  "iad-to-washington-dc": {
    metaTitle: "Dulles (IAD) to Washington DC Car Service | 92 Limo Service",
    metaDescription:
      "Private car service from Washington Dulles (IAD) to Washington DC. International arrivals, meet & greet, flight tracking, and flat-rate pricing.",
    eyebrow: "IAD → WASHINGTON DC",
    h1: "Dulles (IAD) to Washington DC Car Service",
    subtitle: "Relaxed, chauffeured transfers from Washington Dulles into the capital — about 26 miles after a long flight.",
    image: IMAGES.corporate,
    alt: "Executive entering a luxury vehicle for IAD to DC car service",
    highlightsHeading: "The Calm After a Long Flight",
    intro: [
      "Washington Dulles International (IAD) is the region's primary gateway for international and long-haul flights, sitting about 26 miles west of downtown Washington in Virginia. After a long journey, the last thing you want is to navigate the Dulles Toll Road and Beltway yourself — so 92 Limo Service is waiting with a meet & greet, luggage assistance, and a quiet luxury vehicle to carry you the rest of the way in comfort.",
      "Travel time from Dulles to downtown DC typically runs 40 to 60 minutes depending on traffic, and our chauffeurs monitor conditions to choose the fastest route. For international arrivals, we track your flight and account for customs and immigration time, so your chauffeur is ready exactly when you emerge — not circling or charging you to wait.",
      "Diplomats, executives, and leisure travelers alike rely on us for the IAD–DC transfer because it sets the tone for the entire trip: professional, punctual, and effortless. We quote one flat, all-inclusive rate in advance — covering tolls, taxes, and gratuity — with no surge pricing no matter when you land.",
      "Choose the Mercedes-Benz E-Class or BMW 7 Series for solo and business travel, or a Cadillac Escalade, Suburban, or Sprinter van for families and groups arriving with luggage. And with 24/7 service, your overnight international arrival or pre-dawn departure is always covered.",
      "For travelers arriving from overseas, that first ground transfer sets the tone, so we make it calm and seamless: no haggling, no taxi line after a transatlantic flight, and a chauffeur waiting with a name sign the moment you clear customs. We routinely serve embassies, international organizations, and corporate visitors, and we are glad to arrange recurring service for teams and dignitaries who travel through Dulles often — always at a flat, agreed rate quoted before the trip.",
    ],
    highlights: [
      { title: "International Arrivals", desc: "We track your flight and allow for customs and immigration so your chauffeur is ready when you clear." },
      { title: "Meet & Greet at IAD", desc: "Greeted with a name sign and luggage assistance after your long flight." },
      { title: "Direct to Downtown DC", desc: "Door-to-door service to DC hotels, offices, embassies, and residences." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — never surge-priced." },
      { title: "Executive & Diplomatic Travel", desc: "Discreet, professional chauffeurs trusted for high-profile travel." },
      { title: "24/7 Availability", desc: "Overnight international arrivals and pre-dawn departures are no problem." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is Dulles from downtown DC?", a: "About 26 miles, typically a 40 to 60 minute drive depending on traffic on the Dulles Toll Road and I-66 or I-495." },
      { q: "Do you account for customs on international arrivals?", a: "Yes. We track international flights and allow time for customs and immigration, so your chauffeur meets you when you actually clear — not before." },
      { q: "Will I be met inside the terminal?", a: "Yes — meet & greet with a name sign and luggage help is available, as is curbside pickup if you prefer." },
      { q: "Is the price fixed?", a: "Yes, every IAD–DC transfer is quoted as a flat, all-inclusive rate covering tolls, taxes, and gratuity." },
      { q: "Can you accommodate families and groups?", a: "Absolutely — SUVs and Sprinter vans offer ample seating and luggage space for groups arriving together." },
      { q: "Do you offer return service to Dulles?", a: "Yes, 24/7, including early-morning departures for international flights." },
      { q: "Can you greet international or VIP guests at the terminal?", a: "Yes. Our chauffeurs are experienced with international and VIP arrivals, providing a courteous meet-and-greet with a name sign, luggage assistance, and discreet, professional service from the terminal to the final destination. We can coordinate the details in advance for dignitaries and corporate guests." },
    ],
    ctaTitle: "Book Your IAD–DC Transfer",
    ctaSubtitle: "Reserve a chauffeur from Dulles into Washington, D.C. with flat, all-inclusive pricing.",
  },

  "bwi-to-columbia": {
    metaTitle: "BWI Airport to Columbia, MD Car Service | 92 Limo Service",
    metaDescription:
      "Luxury car service from BWI Airport to Columbia, MD. Flight tracking, meet & greet, and flat-rate transfers to Merriweather and Howard County.",
    eyebrow: "BWI → COLUMBIA",
    h1: "BWI Airport to Columbia, MD Car Service",
    subtitle: "Comfortable chauffeured transfers between BWI Marshall and Columbia — about 15 miles into Howard County, with flat-rate pricing and around-the-clock availability.",
    image: IMAGES.sedan,
    alt: "Luxury sedan for BWI to Columbia car service",
    highlightsHeading: "Howard County Comfort",
    intro: [
      "Columbia is the heart of Howard County — a planned community known for Merriweather Post Pavilion, the bustling Columbia Town Center, top employers, and easy access between Baltimore and Washington. 92 Limo Service provides luxury chauffeured transfers between BWI Marshall Airport and Columbia, a short trip of roughly 15 miles, with the reliability and polish that business and leisure travelers count on.",
      "The drive typically takes 20 to 30 minutes via I-95 and MD-100 or US-29, and our chauffeurs know the quickest routes to Columbia's villages, the Town Center hotels, the Mall in Columbia, and the area's corporate campuses. We meet you at baggage claim, handle your luggage, and provide a comfortable, quiet ride whether you are traveling for work or heading home.",
      "Concert-goers love arriving at Merriweather Post Pavilion without the parking crush, and business travelers appreciate dependable, fixed-rate service to Howard County's employers and conference venues. We track your inbound flight, adjust for delays automatically, and quote one transparent, all-inclusive price — no metering and no surge.",
      "From the Mercedes-Benz E-Class for individuals to SUVs and Sprinter vans for families and groups with luggage, we match the right vehicle to your trip, with 24/7 availability for early departures and late arrivals back to BWI, DCA, or IAD.",
      "Columbia's village layout can confuse out-of-town drivers, but our chauffeurs know the community's roads, the Town Center, and the corporate parks well, getting you to the right entrance the first time. Concert nights at Merriweather Post Pavilion are a specialty — we drop you close, skip the parking gridlock, and meet you afterward at an agreed spot so you are not searching a packed lot in the dark. Reliable, fixed-rate, and available around the clock.",
    ],
    highlights: [
      { title: "Merriweather Post Pavilion", desc: "Arrive at concerts and events without the parking crush — drop-off and pickup handled." },
      { title: "Town Center & Corporate Campuses", desc: "Reliable transfers to Columbia hotels, the Mall, and Howard County employers." },
      { title: "Short 20–30 Minute Trip", desc: "Only about 15 miles from BWI via I-95 and MD-100 or US-29." },
      { title: "Meet & Greet + Flight Tracking", desc: "Greeted at baggage claim; we monitor your flight and adjust for delays." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — no metering and no surprises, even on busy event nights." },
      { title: "24/7 Service", desc: "Around-the-clock chauffeurs for early departures, late arrivals, and post-concert returns." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is Columbia from BWI?", a: "About 15 miles — typically a 20 to 30 minute drive via I-95 and MD-100 or US-29." },
      { q: "Can you drop me at Merriweather Post Pavilion?", a: "Yes. We provide concert and event transfers to Merriweather with convenient drop-off and a coordinated post-event pickup." },
      { q: "Do you serve Howard County businesses?", a: "Yes — we regularly transfer business travelers to Columbia's corporate campuses, hotels, and conference venues." },
      { q: "What if my flight is delayed?", a: "We track your flight and adjust pickup automatically, with no extra charge for reasonable delays." },
      { q: "Is the price fixed?", a: "Yes, every BWI–Columbia transfer is quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Can you take groups?", a: "Absolutely — SUVs and Sprinter vans handle families, groups, and luggage with ease." },
      { q: "Do you serve Merriweather events and Columbia corporate parks together?", a: "Yes. We handle both concert nights at Merriweather Post Pavilion and weekday corporate travel to Columbia's business campuses, and we can combine them — for example, a daytime meeting followed by an evening show — on a single hourly or point-to-point reservation. Groups ride together in our SUVs and Sprinter vans, and every rate is quoted in advance with no surge." },
    ],
    ctaTitle: "Book Your Columbia Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Columbia with flat, all-inclusive pricing.",
  },

  "bwi-to-arlington": {
    metaTitle: "BWI Airport to Arlington, VA Car Service | 92 Limo Service",
    metaDescription:
      "Private car service from BWI Airport to Arlington, VA. Flight tracking, meet & greet, and flat-rate transfers to the Pentagon, Crystal City & Rosslyn.",
    eyebrow: "BWI → ARLINGTON",
    h1: "BWI Airport to Arlington, VA Car Service",
    subtitle: "Professional chauffeured transfers between BWI Marshall and Arlington, Virginia — about 40 miles, with flat-rate pricing and 24/7 service for government and corporate travelers.",
    image: IMAGES.suv,
    alt: "Luxury SUV for BWI to Arlington car service",
    highlightsHeading: "Northern Virginia, Done Right",
    intro: [
      "Arlington, Virginia packs an extraordinary amount into a compact county — the Pentagon, Arlington National Cemetery, the business hubs of Rosslyn, Crystal City, and Ballston, and Amazon's HQ2 in National Landing. 92 Limo Service provides luxury chauffeured transfers between BWI Marshall Airport and Arlington, a trip of roughly 40 miles, with the punctual professionalism that government and corporate travelers require.",
      "Travel time typically runs 50 to 75 minutes depending on traffic on I-95 and across the Potomac, and our chauffeurs plan around the region's notorious rush hours to keep you on schedule. We meet you at baggage claim, take your luggage, and provide a quiet cabin where you can prepare for a meeting or unwind after a flight.",
      "Arlington's mix of federal agencies, defense contractors, and fast-growing tech employers makes dependable, fixed-rate ground transportation essential — and far more comfortable than rideshare roulette. We track your inbound flight, adjust automatically for delays, and quote one transparent, all-inclusive rate with no surge pricing.",
      "Choose the Mercedes-Benz E-Class or BMW 7 Series for executive travel, or a Cadillac Escalade, Suburban, or Sprinter van for groups and luggage. With 24/7 service, your earliest departure or latest arrival to BWI, Reagan, or Dulles is always covered.",
      "Arlington's dense mix of government, defense, and tech destinations rewards a chauffeur who knows the area, and ours navigate the Pentagon reservation, National Landing, and the Rosslyn-Ballston corridor with ease. Security-conscious clients appreciate punctual, professional service and clean vehicles, while frequent travelers appreciate predictable flat pricing instead of fluctuating rideshare fares. Tell us your destination and timing and we will recommend the most efficient airport and route for your trip.",
    ],
    highlights: [
      { title: "Pentagon & National Landing", desc: "Reliable transfers to the Pentagon, Crystal City, and Amazon's National Landing." },
      { title: "Rosslyn & Ballston", desc: "Door-to-door service to Arlington's business corridors and hotels." },
      { title: "Government & Corporate Travel", desc: "Punctual, discreet chauffeurs trusted by federal and corporate clients." },
      { title: "Meet & Greet + Flight Tracking", desc: "Greeted at baggage claim; we monitor your flight and adjust for delays." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — no surge." },
      { title: "24/7 Availability", desc: "Around-the-clock service for early departures and late arrivals." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is Arlington from BWI?", a: "About 40 miles, typically a 50 to 75 minute drive depending on traffic on I-95 and the Potomac crossings." },
      { q: "Do you serve the Pentagon and National Landing?", a: "Yes — we provide door-to-door transfers to the Pentagon, Crystal City, National Landing, Rosslyn, and Ballston." },
      { q: "Is this suitable for government and corporate travel?", a: "Very much so. Our chauffeurs are punctual and discreet, and we can set up recurring corporate accounts for frequent travelers." },
      { q: "What if my flight is delayed?", a: "We track your flight and adjust pickup automatically, with no extra charge for reasonable delays." },
      { q: "Is the price fixed?", a: "Yes, every BWI–Arlington transfer is quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Would DCA be closer for Arlington?", a: "Often, yes — Reagan National is very close to Arlington. We serve transfers from DCA, BWI, and IAD, so we'll advise the best option for your trip." },
      { q: "Do you provide ongoing corporate accounts for Arlington businesses?", a: "Yes. Government contractors, agencies, and tech employers across Arlington rely on us for recurring executive travel, client pickups, and team transfers. We can establish a corporate account with consolidated billing, saved traveler profiles, and priority scheduling, so booking a polished, on-time ride is effortless every time you need one — to the Pentagon, National Landing, Reagan National, or anywhere across the DMV." },
    ],
    ctaTitle: "Book Your Arlington Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Arlington with flat, all-inclusive pricing.",
  },

  "bwi-to-alexandria": {
    metaTitle: "BWI Airport to Alexandria, VA Car Service | 92 Limo Service",
    metaDescription:
      "Luxury car service from BWI Airport to Alexandria, VA. Flight tracking, meet & greet, and flat-rate transfers to Old Town and the waterfront.",
    eyebrow: "BWI → ALEXANDRIA",
    h1: "BWI Airport to Alexandria, VA Car Service",
    subtitle: "Elegant chauffeured transfers between BWI Marshall and historic Alexandria — about 45 miles, with flat-rate pricing and 24/7 availability for Old Town and beyond.",
    image: IMAGES.sClassFirst,
    alt: "Mercedes-Benz S-Class for BWI to Alexandria car service",
    highlightsHeading: "Old Town Elegance",
    intro: [
      "Alexandria, Virginia charms visitors with its cobblestone streets, waterfront, and the historic shops and restaurants of Old Town — while also serving as a base for business travelers working across Northern Virginia and DC. 92 Limo Service provides luxury chauffeured transfers between BWI Marshall Airport and Alexandria, a trip of roughly 45 miles, delivering the comfort and reliability the occasion deserves.",
      "Travel time typically runs 55 to 80 minutes depending on traffic on I-95 and the Beltway, and our chauffeurs plan around congestion to keep you on time. We meet you at baggage claim, handle your luggage, and provide a refined, quiet cabin for the ride to your Old Town hotel, a waterfront restaurant, a residence, or a business meeting.",
      "Whether you are visiting for a romantic Old Town weekend, a wedding, a conference, or a corporate engagement, you will appreciate arriving relaxed and on schedule. We track your inbound flight, adjust automatically for delays, and quote one flat, all-inclusive price — covering tolls, taxes, and gratuity — with no surge pricing.",
      "From the Mercedes-Benz E-Class and BMW 7 Series for couples and executives to SUVs and Sprinter vans for families and groups with luggage, we right-size the vehicle to your trip, and we are available 24/7 for departures back to BWI, Reagan, or Dulles.",
      "Old Town's cobblestone streets and limited parking can be a headache behind the wheel, so let your chauffeur handle it — dropping you steps from your King Street restaurant, waterfront hotel, or event venue. We are a popular choice for anniversaries, proposals, and weddings, where a polished arrival matters, as well as for business travelers working across Northern Virginia. Every trip is quoted up front, with no surge and no surprises, day or night.",
    ],
    highlights: [
      { title: "Old Town Alexandria", desc: "Direct service to Old Town hotels, the waterfront, King Street, and historic district." },
      { title: "Weddings & Weekends", desc: "Elegant transport for romantic getaways, weddings, and special occasions." },
      { title: "Meet & Greet at BWI", desc: "Greeted at baggage claim with a name sign and luggage assistance." },
      { title: "Flight Tracking", desc: "We monitor your flight and adjust for early arrivals or delays automatically." },
      { title: "Flat-Rate Pricing", desc: "All-inclusive quotes covering tolls, taxes, and gratuity — no surge pricing." },
      { title: "24/7 Service", desc: "Around-the-clock chauffeurs for every arrival and departure." },
    ],
    vehicles: SEDAN_TRIO,
    faqs: [
      { q: "How far is Alexandria from BWI?", a: "About 45 miles, typically a 55 to 80 minute drive depending on traffic on I-95 and the Beltway." },
      { q: "Do you serve Old Town Alexandria?", a: "Yes — we provide door-to-door service to Old Town hotels, the waterfront, King Street, and residences throughout Alexandria." },
      { q: "Is this a good option for a wedding or special occasion?", a: "Absolutely. Our luxury sedans and SUVs are ideal for weddings, anniversaries, and romantic weekends in Old Town." },
      { q: "What if my flight is delayed?", a: "We track your flight and adjust pickup automatically, with no extra charge for reasonable delays." },
      { q: "Is the fare fixed?", a: "Yes, every BWI–Alexandria transfer is quoted as a flat, all-inclusive rate with no surge pricing." },
      { q: "Would another airport be closer?", a: "Reagan National (DCA) is closer to Alexandria. We serve DCA, BWI, and IAD, so we'll help you choose the best airport for your trip." },
      { q: "Can you arrange a special-occasion ride in Old Town?", a: "Definitely. For weddings, anniversaries, proposals, and milestone celebrations in Old Town Alexandria, we provide an elegant, chauffeured arrival in a spotless luxury vehicle, with the timing planned around your reservation or ceremony. It's a memorable way to mark the moment without worrying about parking or driving — ask about our sedans, SUVs, and limousine." },
    ],
    ctaTitle: "Book Your Alexandria Transfer",
    ctaSubtitle: "Reserve a chauffeur between BWI and Alexandria with flat, all-inclusive pricing.",
  },

  // ---------------------------------------------------------------- BEACHES
  "bwi-to-bethany-beach": {
    metaTitle: "BWI to Bethany Beach Car Service | 92 Limo Service",
    metaDescription:
      "Luxury long-distance car service from BWI Airport to Bethany Beach, DE. Flat-rate, no-surge pricing with roomy SUVs and Sprinter vans for groups.",
    eyebrow: "BWI → BETHANY BEACH",
    h1: "BWI to Bethany Beach Car Service",
    subtitle: "Relaxed, chauffeured long-distance transfers from BWI to Delaware's 'quiet resort' — about 2.5 hours of comfort.",
    image: IMAGES.longDistance,
    alt: "Luxury vehicle on a long-distance beach transfer to Bethany Beach",
    highlightsHeading: "Arrive at the Shore Refreshed",
    intro: [
      "Bethany Beach, Delaware — affectionately known as one of the state's 'Quiet Resorts' — is a favorite for families seeking a calmer, more relaxed shore vacation. The catch is the drive: roughly 2.5 hours from BWI Marshall Airport, much of it on busy summer routes. 92 Limo Service turns that long haul into the easiest part of your trip with comfortable, chauffeured long-distance transfers and flat-rate pricing that never surges.",
      "Instead of renting a car, fighting beach traffic, and paying for a week of parking, you settle into a spacious, climate-controlled luxury vehicle while a professional chauffeur handles the entire drive down US-50 and Route 1. Kids can nap, parents can relax, and everyone arrives at the rental house or hotel refreshed rather than frazzled — with all the luggage, beach chairs, and coolers handled for you.",
      "For families and groups, our Mercedes Sprinter vans and full-size SUVs are ideal: plenty of seating to keep everyone together, generous cargo space for a week's worth of bags and gear, and a smooth, quiet ride for the longer journey. We quote a flat, all-inclusive rate up front — covering tolls, taxes, and gratuity — so there is no meter ticking through beach-season traffic and no surge pricing on busy summer weekends.",
      "We also provide the return trip back to BWI (or DCA/IAD) at the end of your stay, timed to your flight with our usual flight tracking and punctuality. Whether it is a family vacation, a multi-generational reunion, or a group of friends heading to the shore, we make the door-to-beach journey effortless.",
      "Many of our beach clients book the same chauffeur for the entire week — a grocery run after arrival, a dinner reservation in nearby Fenwick Island or downtown Bethany, and the return trip home — so they never need a rental car at all. With a professional handling the long drive in both directions, the vacation truly starts the moment you are picked up. Reserve early for peak summer weekends, when demand for our Sprinter vans and SUVs is highest.",
    ],
    highlights: [
      { title: "Comfort for the Long Drive", desc: "Spacious, climate-controlled cabins make the ~2.5-hour journey genuinely relaxing." },
      { title: "Flat Rate, No Surge", desc: "One all-inclusive price quoted up front — never surge-priced on busy summer weekends." },
      { title: "Sprinter Vans for Groups", desc: "Keep families and groups together with room for a week's worth of luggage and beach gear." },
      { title: "Full Luggage & Gear Space", desc: "Beach chairs, coolers, and bags handled — no squeezing into a packed car." },
      { title: "No Rental Car or Parking", desc: "Skip the rental counter, beach traffic stress, and a week of parking fees." },
      { title: "Round-Trip Service", desc: "We bring you home too, timed to your return flight with flight tracking." },
    ],
    vehicles: BEACH_TRIO,
    faqs: [
      { q: "How long is the drive from BWI to Bethany Beach?", a: "Roughly 2.5 hours depending on season and traffic, traveling via US-50 and Delaware Route 1." },
      { q: "Is the price flat or metered?", a: "Flat and all-inclusive. We quote one price up front covering tolls, taxes, and gratuity — with no surge pricing, even on peak summer weekends." },
      { q: "Can you fit my whole family and our luggage?", a: "Yes. Our Sprinter vans and full-size SUVs seat groups comfortably with generous cargo space for luggage, beach chairs, and coolers." },
      { q: "Do you provide the return trip to the airport?", a: "Yes — we handle round-trip service and time your return to BWI, DCA, or IAD around your flight, with flight tracking." },
      { q: "Why choose a chauffeur over a rental car?", a: "You skip the rental counter, the stressful beach-season traffic, and a week of parking fees — and you arrive relaxed instead of worn out from driving." },
      { q: "How far in advance should I book?", a: "Summer weekends fill quickly, so we recommend booking as early as possible. Call 877-679-0100 anytime, 24/7." },
    ],
    ctaTitle: "Book Your Bethany Beach Transfer",
    ctaSubtitle: "Reserve a comfortable, flat-rate chauffeur to Bethany Beach — no surge, no stress.",
  },

  "bwi-to-rehoboth-beach": {
    metaTitle: "BWI to Rehoboth Beach Car Service | 92 Limo Service",
    metaDescription:
      "Luxury long-distance car service from BWI Airport to Rehoboth Beach, DE. Flat-rate, no-surge pricing with roomy SUVs and Sprinter vans for groups.",
    eyebrow: "BWI → REHOBOTH BEACH",
    h1: "BWI to Rehoboth Beach Car Service",
    subtitle: "Chauffeured long-distance transfers from BWI to Rehoboth's boardwalk and outlets — about 2.5 hours of ease.",
    image: IMAGES.longDistance,
    alt: "Luxury vehicle on a long-distance beach transfer to Rehoboth Beach",
    highlightsHeading: "Boardwalk-Bound in Comfort",
    intro: [
      "Rehoboth Beach, Delaware is the liveliest of the Delaware beaches — famous for its mile-long boardwalk, tax-free outlet shopping, and a buzzing restaurant scene. It is also about 2.5 hours from BWI Marshall Airport, and the summer drive can test anyone's patience. 92 Limo Service makes the journey the easy part with comfortable, chauffeured long-distance transfers and honest, flat-rate pricing.",
      "Rather than renting a car and battling Route 1 beach traffic, you relax in a spacious luxury vehicle while a professional chauffeur drives the full route via US-50 and Delaware Route 1. The cabin is climate-controlled and quiet, your luggage and beach gear are loaded for you, and you step out at your hotel, rental, or the boardwalk rested and ready to enjoy the shore.",
      "Families and groups travel best in our Mercedes Sprinter vans and full-size SUVs — everyone stays together, there is real room for a week of bags, and the ride stays smooth over the longer distance. We quote a flat, all-inclusive rate in advance covering tolls, taxes, and gratuity, with absolutely no surge pricing on peak weekends or holidays.",
      "At the end of your trip, we bring you back to BWI (or DCA/IAD) on a schedule built around your flight, with flight tracking and our usual punctuality. From a couples' getaway to a big group of friends or a multi-family reunion, we make the door-to-boardwalk trip seamless.",
      "Rehoboth's combination of beach, boardwalk, dining, and tax-free outlet shopping makes it a full-week destination, and many guests keep us on call throughout their stay rather than renting a car. From a dinner downtown to an outlet shopping haul that fills the cargo area, our chauffeurs and roomy vehicles handle it all. Book early for holiday weekends and summer Saturdays, when our larger group vehicles go quickly.",
    ],
    highlights: [
      { title: "Straight to the Boardwalk", desc: "Door-to-door service to Rehoboth hotels, rentals, and the boardwalk." },
      { title: "Flat Rate, No Surge", desc: "One all-inclusive price up front — never surge-priced on peak weekends or holidays." },
      { title: "Comfort Over the Long Haul", desc: "A spacious, quiet, climate-controlled cabin makes the ~2.5-hour drive relaxing." },
      { title: "Sprinter Vans for Groups", desc: "Keep your whole party together with room for a week of luggage and gear." },
      { title: "No Rental or Beach Traffic Stress", desc: "Skip the rental counter, Route 1 congestion, and parking fees entirely." },
      { title: "Round-Trip & Outlet-Ready", desc: "We handle the return trip too — perfect for a tax-free outlet shopping haul." },
    ],
    vehicles: BEACH_TRIO,
    faqs: [
      { q: "How long is the drive from BWI to Rehoboth Beach?", a: "Roughly 2.5 hours depending on season and traffic, via US-50 and Delaware Route 1." },
      { q: "Is pricing flat?", a: "Yes — flat and all-inclusive, covering tolls, taxes, and gratuity, with no surge pricing on busy weekends or holidays." },
      { q: "Can you carry a big group and lots of luggage?", a: "Yes. Sprinter vans and full-size SUVs keep groups together with generous space for luggage, beach gear, and outlet shopping hauls." },
      { q: "Do you offer the return trip to the airport?", a: "Yes, round-trip service timed to your departure from BWI, DCA, or IAD, with flight tracking." },
      { q: "Why not just rent a car?", a: "A chauffeur means no rental counter, no fighting Route 1 traffic, no parking fees — and you arrive relaxed instead of drained." },
      { q: "How early should I reserve?", a: "Peak-season weekends book up fast, so reserve early. We're available 24/7 at 877-679-0100." },
      { q: "Can you stop at the outlets or for groceries on the way in?", a: "Yes. Just let us know when you book — we're happy to add a quick stop at the Tanger Outlets or a grocery store so your rental is stocked before you arrive. Our roomy SUVs and Sprinter vans have plenty of cargo space for the haul." },
    ],
    ctaTitle: "Book Your Rehoboth Beach Transfer",
    ctaSubtitle: "Reserve a comfortable, flat-rate chauffeur to Rehoboth Beach — no surge, no stress.",
  },

  "bwi-to-ocean-city-md": {
    metaTitle: "BWI to Ocean City MD Car Service | 92 Limo Service",
    metaDescription:
      "Luxury long-distance car service from BWI Airport to Ocean City, MD. Flat-rate, no-surge pricing with roomy SUVs and Sprinter vans for groups.",
    eyebrow: "BWI → OCEAN CITY, MD",
    h1: "BWI to Ocean City MD Car Service",
    subtitle: "Chauffeured long-distance transfers from BWI to OCMD's boardwalk and beaches — about 2.5 to 3 hours in comfort.",
    image: IMAGES.longDistance,
    alt: "Luxury vehicle on a long-distance beach transfer to Ocean City Maryland",
    highlightsHeading: "OCMD Without the Drive",
    intro: [
      "Ocean City, Maryland is the Mid-Atlantic's classic beach destination — ten miles of beach, a famous boardwalk, and a summer energy that draws families and groups from all over. It is also a solid 2.5 to 3 hours from BWI Marshall Airport, much of it on heavily traveled summer routes. 92 Limo Service makes the trek effortless with comfortable, chauffeured long-distance transfers and flat-rate pricing that never surges.",
      "Skip the rental car, the bumper-to-bumper crawl across the Bay Bridge, and the hunt for parking near the boardwalk. Instead, you relax in a spacious luxury vehicle while a professional chauffeur handles the full drive via US-50 and the Chesapeake Bay Bridge. The cabin stays cool and quiet, your luggage and beach gear are loaded for you, and you arrive at your condo, hotel, or rental ready to hit the sand.",
      "For families and groups, our Mercedes Sprinter vans and full-size SUVs are the ideal way to travel: everyone stays together, there is generous room for a week of bags, boards, and coolers, and the ride stays smooth over the longer distance. We quote a flat, all-inclusive rate up front — covering tolls (including the Bay Bridge), taxes, and gratuity — with no surge pricing on peak summer weekends.",
      "When your vacation wraps, we bring you back to BWI (or DCA/IAD) on a schedule built around your flight, with flight tracking and dependable punctuality. From a family beach week to a group celebration, we make the door-to-boardwalk journey easy from start to finish.",
      "Because OCMD draws huge summer crowds, the timing of your departure matters, and our chauffeurs plan around Bay Bridge backups and weekend beach traffic to keep your trip as smooth as possible. Families love that the kids can sleep or watch a movie while a professional drives; groups love staying together in one comfortable vehicle. From mid-week getaways to peak Saturday turnovers, reserve early to lock in your preferred Sprinter van or SUV at a guaranteed flat rate.",
    ],
    highlights: [
      { title: "Boardwalk & Beaches", desc: "Door-to-door service to OCMD condos, hotels, rentals, and the boardwalk." },
      { title: "Bay Bridge Handled", desc: "Relax while your chauffeur manages the Chesapeake Bay Bridge crossing and summer traffic." },
      { title: "Flat Rate, No Surge", desc: "One all-inclusive price up front — tolls included, never surge-priced." },
      { title: "Sprinter Vans for Groups", desc: "Keep families and groups together with room for a week of luggage and beach gear." },
      { title: "No Rental or Parking Hassle", desc: "Skip the rental counter and the search for boardwalk parking entirely." },
      { title: "Round-Trip Service", desc: "We handle the return to BWI, DCA, or IAD, timed to your flight." },
    ],
    vehicles: BEACH_TRIO,
    faqs: [
      { q: "How long is the drive from BWI to Ocean City, MD?", a: "Roughly 2.5 to 3 hours depending on season and traffic, via US-50 and the Chesapeake Bay Bridge." },
      { q: "Are the Bay Bridge tolls included?", a: "Yes. Our flat, all-inclusive rate covers tolls (including the Bay Bridge), taxes, and gratuity, with no surge pricing." },
      { q: "Can you accommodate a large beach group?", a: "Absolutely — Sprinter vans and full-size SUVs seat groups comfortably with generous cargo space for luggage, boards, and coolers." },
      { q: "Do you provide the return trip?", a: "Yes, round-trip service timed to your departure from BWI, DCA, or IAD with flight tracking." },
      { q: "Is a chauffeur better than driving myself?", a: "For most travelers, yes — no rental car, no Bay Bridge stress, no parking hunt, and you arrive rested and ready for the beach." },
      { q: "When should I book for summer?", a: "As early as possible — peak weekends sell out. Call 877-679-0100 anytime, 24/7." },
      { q: "Do you offer round-trip and mid-week beach rates?", a: "Yes. We provide round-trip service timed to your return, and mid-week travel often offers the smoothest drive of the week. Ask for a flat quote for your specific dates when you book." },
    ],
    ctaTitle: "Book Your Ocean City Transfer",
    ctaSubtitle: "Reserve a comfortable, flat-rate chauffeur to Ocean City, MD — no surge, no stress.",
  },

  "dc-to-bethany-beach": {
    metaTitle: "Washington DC to Bethany Beach Car Service | 92 Limo Service",
    metaDescription:
      "Luxury long-distance car service from Washington DC to Bethany Beach, DE. Flat-rate, no-surge pricing with roomy SUVs and Sprinter vans for groups.",
    eyebrow: "WASHINGTON DC → BETHANY BEACH",
    h1: "Washington DC to Bethany Beach Car Service",
    subtitle: "Chauffeured long-distance transfers from DC to Delaware's quiet resort — about 3 hours of effortless comfort.",
    image: IMAGES.longDistance,
    alt: "Luxury vehicle on a long-distance beach transfer from DC to Bethany Beach",
    highlightsHeading: "From the Capital to the Coast",
    intro: [
      "Trading the bustle of the capital for the calm of the Delaware shore is one of the best ways to unwind — but the drive from Washington, D.C. to Bethany Beach is about three hours, much of it through summer beach traffic. 92 Limo Service makes that journey the easy part of your getaway with comfortable, chauffeured long-distance transfers and flat-rate pricing that never surges.",
      "We pick you up at your DC home, hotel, or office and handle the entire drive east via US-50 and Delaware Route 1, while you stretch out in a spacious, climate-controlled luxury vehicle. There is no rental car to manage, no Bay Bridge stress to white-knuckle, and no week of beach parking fees — just a smooth, quiet ride with your luggage and beach gear loaded for you.",
      "Families and groups travel best in our Mercedes Sprinter vans and full-size SUVs: room to keep everyone together, generous cargo space for a week of bags, and the comfort that makes a three-hour drive feel short. We quote a flat, all-inclusive rate in advance — covering tolls, taxes, and gratuity — with no surge pricing on busy weekends or holidays.",
      "At the end of your stay, we bring you back to DC (or to BWI, DCA, or IAD if you are flying onward) on a schedule that suits you. Whether it is a family vacation, a couples' retreat, or a group escape to the quiet resort, we make the door-to-beach trip seamless in both directions.",
      "City dwellers without a car of their own find our door-to-beach service especially convenient — there is no rental counter, no need to navigate out of the city, and no parking to arrange at the shore. We pick up anywhere in the District and the close-in suburbs, and we are happy to coordinate a multi-stop pickup if your group is gathering from different addresses. Reserve early for summer weekends and holidays, when our group vehicles book up fast.",
    ],
    highlights: [
      { title: "Door-to-Beach From DC", desc: "Pickup at your DC home, hotel, or office and direct service to Bethany Beach." },
      { title: "Comfort for ~3 Hours", desc: "A spacious, quiet, climate-controlled cabin makes the long drive genuinely relaxing." },
      { title: "Flat Rate, No Surge", desc: "One all-inclusive price up front — never surge-priced on peak weekends or holidays." },
      { title: "Sprinter Vans for Groups", desc: "Keep families and groups together with room for a week of luggage and beach gear." },
      { title: "No Rental or Parking Hassle", desc: "Skip the rental car, Bay Bridge traffic, and a week of beach parking fees." },
      { title: "Round-Trip or Airport Onward", desc: "We bring you back to DC or on to BWI, DCA, or IAD if you're flying out." },
    ],
    vehicles: BEACH_TRIO,
    faqs: [
      { q: "How long is the drive from DC to Bethany Beach?", a: "About 3 hours depending on season and traffic, traveling via US-50 and Delaware Route 1." },
      { q: "Is the price flat?", a: "Yes — flat and all-inclusive, covering tolls, taxes, and gratuity, with no surge pricing even on peak weekends." },
      { q: "Can you carry a family or group with a week of luggage?", a: "Yes. Sprinter vans and full-size SUVs keep groups together with generous luggage and beach-gear capacity." },
      { q: "Do you provide the return trip?", a: "Yes — round-trip service back to DC, or onward to BWI, DCA, or IAD if you're flying home." },
      { q: "Why choose a chauffeur for a beach trip?", a: "No rental car, no Bay Bridge stress, no parking fees — and everyone, including the driver, actually gets to relax on the way to the shore." },
      { q: "How far ahead should I book?", a: "Summer weekends book up early, so reserve as soon as your plans are set. We're available 24/7 at 877-679-0100." },
    ],
    ctaTitle: "Book Your DC–Bethany Beach Transfer",
    ctaSubtitle: "Reserve a comfortable, flat-rate chauffeur from DC to Bethany Beach — no surge, no stress.",
  },
};

// Slugs grouped for navigation / sitemap.
export const ROUTE_SLUGS = [
  "bwi-to-washington-dc",
  "bwi-to-annapolis",
  "bwi-to-baltimore",
  "bwi-to-bethesda",
  "bwi-to-dulles",
  "dca-to-washington-dc",
  "iad-to-washington-dc",
  "bwi-to-columbia",
  "bwi-to-arlington",
  "bwi-to-alexandria",
];

export const BEACH_SLUGS = [
  "bwi-to-bethany-beach",
  "bwi-to-rehoboth-beach",
  "bwi-to-ocean-city-md",
  "dc-to-bethany-beach",
];
