// Batch 5 (2026-09-23): BWI and DCA keyword-cluster pages — 4 BWI routes, 3 BWI
// services, 6 DCA routes, 1 DCA service. Same entry shape as
// MARYLAND_BATCH4_PAGES; merged into LANDING_PAGES by landingPages.js.
export const MARYLAND_BATCH5_PAGES = {
  "bwi-to-laurel-md": {
    metaTitle: "BWI to Laurel, MD Car Service | 92 Limo Service",
    metaDescription: "BWI Airport to Laurel, MD car service from the company based right in Laurel. Flat-rate transfers, flight tracking, 24/7. Call (877) 609-1919.",
    eyebrow: "BWI → LAUREL, MD",
    h1: "BWI to Laurel, MD Car Service",
    subtitle: "The shortest trip on our schedule — 92 Limo Service is based in Laurel, and a BWI transfer home or to the office is one of the routes our chauffeurs know best.",
    image: "/images/site/sedan.webp",
    alt: "Chauffeured sedan for BWI Airport to Laurel, MD car service — 92 Limo Service",
    highlightsHeading: "Why Laurel Trusts the Local Company",
    intro: [
      "92 Limo Service is headquartered at 9836 Lyon Ave in Laurel, Maryland, which makes BWI to Laurel car service the one route we could run with our eyes closed. Laurel sits about 15 miles from BWI Marshall Airport, a straightforward run down MD-295 (the Baltimore-Washington Parkway) or I-95 depending on traffic, and our chauffeurs make this drive constantly — for our own dispatch team's airport pickups as much as for our neighbors'.",
      "That local presence is not just a talking point. When you book a Laurel pickup, your chauffeur is coming from minutes away, not crossing the region to reach you, which matters most on the trips where timing is tight: a pre-dawn departure, a late connection into BWI, or a same-day request that a company based somewhere else would struggle to cover.",
      "Laurel residents and businesses use us for more than the airport. Fort Meade employees book us for early-morning shifts, families near Konterra and Brock Bridge use us for weddings and proms at venues across the DMV, and Laurel's corporate offices set up accounts with monthly invoicing for staff who fly out of BWI, DCA or IAD regularly.",
      "Every BWI to Laurel transfer includes real-time flight tracking, so your chauffeur is dispatched against your actual arrival, not the printed schedule. Airport pickups include 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international arrivals, and meet & greet inside baggage claim is available for an additional charge if you would rather not scan the curb for your car.",
      "The rate is confirmed before you ride, covering the base transportation charge, with gratuity, tolls and parking disclosed before you confirm. Whether it is a sedan for one traveler or a Sprinter for a Laurel family heading out together, tell us your flight and pickup details and we will have a chauffeur waiting.",
    ],
    highlights: [
      { title: "We're Based Right Here", desc: "92 Limo Service's office is in Laurel, so a BWI-to-Laurel pickup is one of the shortest, most familiar routes we run." },
      { title: "About 15 Miles from BWI", desc: "A straightforward run via MD-295 or I-95, typically 20–30 minutes depending on traffic." },
      { title: "Flight Tracking Included", desc: "Your chauffeur is dispatched against your real arrival time, with 45–60 minutes of complimentary wait built in." },
      { title: "Fort Meade & Corporate Accounts", desc: "Standing pickups and monthly invoicing for Laurel businesses and Fort Meade commuters who fly often." },
      { title: "Meet & Greet Available", desc: "Your chauffeur can meet you inside baggage claim with a name sign for an additional charge." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride — no metering, no surge, even on the busiest travel days." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "Premium SUV — Cadillac Escalade",
      "Sprinter Shuttle — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Laurel Neighborhoods We Cover",
        places: [
          { label: "Downtown Laurel and Main Street" },
          { label: "Konterra and Brock Bridge" },
          { label: "Russett and Maryland City" },
          { label: "Fort Meade" },
        ],
      },
      {
        region: "Related Pages",
        places: [
          { label: "Laurel, MD Limo Service", to: "/laurel-md-limo-service" },
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "BWI to Columbia", to: "/bwi-to-columbia" },
          { label: "BWI Corporate Transportation", to: "/bwi-corporate-transportation" },
          { label: "About 92 Limo Service", to: "/about" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How far is Laurel from BWI Airport?", a: "About 15 miles, typically a 20 to 30 minute drive via MD-295 or I-95 depending on traffic. It is one of the shortest transfers we run, since our office is in Laurel." },
      { q: "Does being based in Laurel actually make the service faster?", a: "Yes. Your chauffeur is often starting the trip minutes from your pickup address rather than crossing the region, which helps most on early-morning or same-day requests." },
      { q: "Do you offer accounts for Laurel businesses with frequent BWI travel?", a: "Yes. Corporate accounts include monthly consolidated invoicing and priority dispatch for companies near Konterra, Fort Meade and downtown Laurel." },
      { q: "What if my flight into BWI is delayed?", a: "Your chauffeur tracks the flight and adjusts the pickup automatically. Airport pickups include 45 minutes of complimentary wait on domestic arrivals and 60 minutes on international." },
      { q: "How much does BWI to Laurel car service cost?", a: "Every trip is quoted as a flat rate before you ride, based on the vehicle class and trip details — call (877) 609-1919 or book online for a confirmed quote; gratuity, tolls and parking are disclosed before you confirm." },
    ],
    ctaTitle: "Book Your BWI to Laurel Transfer",
    ctaSubtitle: "The local company for the local route — call (877) 609-1919 or reserve online.",
  },

  "bwi-to-silver-spring": {
    metaTitle: "BWI to Silver Spring Car Service | 92 Limo Service",
    metaDescription: "Flat-rate BWI Airport to Silver Spring, MD car service. Flight tracking, meet & greet available, 24/7 chauffeurs. Call (877) 609-1919.",
    eyebrow: "BWI → SILVER SPRING, MD",
    h1: "BWI to Silver Spring Car Service",
    subtitle: "Chauffeured transfers between BWI Marshall Airport and Silver Spring's Downtown, Fenton Village and the Discovery District — flat rate, flight-tracked, 24/7.",
    image: "/images/site/suv.webp",
    alt: "Chauffeured SUV for BWI Airport to Silver Spring, MD car service — 92 Limo Service",
    highlightsHeading: "Why Silver Spring Riders Book With Us",
    intro: [
      "Silver Spring is one of Montgomery County's busiest downtowns, home to the AFI Silver Theatre, the Fillmore, the Discovery Building and a dense corridor of apartments and offices along Colesville Road and Georgia Avenue. 92 Limo Service connects that downtown to BWI Marshall Airport with a flat-rate, flight-tracked chauffeur service that runs around the clock.",
      "The drive from BWI to Silver Spring typically runs 45 to 60 minutes, depending on traffic on I-95, the Beltway (I-495) and Georgia Avenue. Because that route crosses some of the region's more congested corridors during rush hour, we back-time departure pickups against real traffic conditions rather than a flat estimate, so you are never left cutting it close to a flight.",
      "Silver Spring residents use us for more than airport runs. Corporate travelers from the office buildings near the Discovery District book us for BWI, DCA and IAD transfers on standing accounts, and Silver Spring families use Sprinter vans and SUVs for weddings, proms and group trips to events across Maryland, DC and Northern Virginia.",
      "Every BWI pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international arrivals. Meet & greet inside baggage claim, with your chauffeur holding a name sign and helping with luggage, is available for an additional charge.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight details and pickup address in Silver Spring, and we will have a licensed, background-checked chauffeur ready.",
    ],
    highlights: [
      { title: "45–60 Minute Trip", desc: "A flat-rate run via I-95, the Beltway and Georgia Avenue, timed against real traffic conditions." },
      { title: "Downtown & Discovery District", desc: "Chauffeurs who know Silver Spring's apartment towers, offices and the AFI Silver Theatre corridor." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare, based on your actual arrival." },
      { title: "Corporate Accounts Available", desc: "Monthly invoicing and priority dispatch for Silver Spring businesses with regular airport travel." },
      { title: "Meet & Greet Option", desc: "Your chauffeur can meet you inside baggage claim with a name sign for an additional charge." },
      { title: "Flat Rate, No Surge", desc: "One confirmed price before you ride, regardless of traffic or time of day." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "Luxury SUV — Chevrolet Suburban",
      "Sprinter Executive — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Silver Spring Areas We Cover",
        places: [
          { label: "Downtown Silver Spring" },
          { label: "Fenton Village" },
          { label: "The Discovery District" },
          { label: "Woodside and Forest Glen" },
        ],
      },
      {
        region: "Related Pages",
        places: [
          { label: "Silver Spring Limo Service", to: "/silver-spring-limo-service" },
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "DCA to Silver Spring", to: "/dca-to-silver-spring" },
          { label: "BWI to Bethesda", to: "/bwi-to-bethesda" },
          { label: "Corporate Transportation", to: "/corporate-transportation" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long is the drive from BWI to Silver Spring?", a: "Typically 45 to 60 minutes via I-95, the Beltway and Georgia Avenue, depending on traffic. We time departure pickups against real conditions, not a flat estimate." },
      { q: "Do you serve the Discovery District and downtown offices?", a: "Yes, including corporate accounts with monthly invoicing for businesses in that corridor with regular airport travel." },
      { q: "Can you pick up a group heading to an event from Silver Spring?", a: "Yes. Sprinter vans and SUVs carry groups and their luggage for weddings, proms and multi-stop days." },
      { q: "What happens if my BWI arrival is delayed?", a: "Your chauffeur tracks the flight and adjusts automatically. Domestic arrivals include 45 minutes of complimentary wait, international arrivals 60 minutes." },
      { q: "What does BWI to Silver Spring car service cost?", a: "Every trip is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, and gratuity, tolls and parking are disclosed before confirmation." },
    ],
    ctaTitle: "Book Your BWI to Silver Spring Transfer",
    ctaSubtitle: "Flat-rate, flight-tracked chauffeur service — call (877) 609-1919 or reserve online.",
  },

  "bwi-to-tysons": {
    metaTitle: "BWI to Tysons Car Service | 92 Limo Service",
    metaDescription: "BWI Airport to Tysons, VA car service for executives and travelers. Flat rate, flight tracking, corporate accounts. Call (877) 609-1919.",
    eyebrow: "BWI → TYSONS, VA",
    h1: "BWI to Tysons Car Service",
    subtitle: "Chauffeured transfers between BWI Marshall Airport and Tysons' corporate corridor — flat rate, flight-tracked, with accounts for standing executive travel.",
    image: "/images/site/s-class.webp",
    alt: "Chauffeured executive sedan for BWI Airport to Tysons, VA car service — 92 Limo Service",
    highlightsHeading: "Built for Tysons' Corporate Travel",
    intro: [
      "Tysons, Virginia is one of the largest office markets on the East Coast, home to corporate headquarters, Tysons Corner Center and Tysons Galleria, and a Metro Silver Line corridor that draws executives from across the region. 92 Limo Service runs a flat-rate, flight-tracked car service between BWI Marshall Airport and Tysons for travelers who need the trip handled without a second thought.",
      "The drive from BWI to Tysons typically takes 60 to 80 minutes, crossing the Baltimore-Washington Parkway or I-95, the Beltway (I-495), and the Dulles Toll Road corridor depending on the exact destination. It is a longer trip than our Maryland routes, which is exactly why we quote it as a confirmed flat rate rather than leaving you guessing at a meter — you know the cost before you book.",
      "Executives and companies headquartered in Tysons use 92 Limo Service for both ends of this route: airport pickups for visiting clients and staff flying into BWI, and departures for Tysons-based travelers heading out. Corporate accounts include monthly consolidated invoicing, priority dispatch, and standing pickups for staff who travel on a predictable schedule.",
      "Every BWI to Tysons pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international arrivals. Meet & greet inside baggage claim is available for an additional charge, useful for visiting executives unfamiliar with BWI's terminal.",
      "The rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Whether it is a single executive sedan or a Sprinter for a visiting team, tell us your flight and Tysons destination and we will handle the rest.",
    ],
    highlights: [
      { title: "60–80 Minute Trip", desc: "A longer regional run via I-95, the Beltway and the Dulles corridor, quoted as a flat rate confirmed before you ride." },
      { title: "Corporate HQ Corridor", desc: "Chauffeurs experienced with Tysons Corner Center, Tysons Galleria and the office towers along the Silver Line." },
      { title: "Standing Executive Accounts", desc: "Monthly invoicing and priority dispatch for Tysons companies with regular staff or client travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time, so a delayed arrival never means a stranded executive." },
      { title: "Meet & Greet for Visitors", desc: "A name-sign pickup inside baggage claim for guests unfamiliar with BWI, for an additional charge." },
      { title: "Flat Rate, No Surprises", desc: "One confirmed price before you ride, regardless of how far the trip runs." },
    ],
    vehicles: [
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
      "Sprinter Executive — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Tysons Destinations We Serve",
        places: [
          { label: "Tysons Corner Center and Tysons Galleria" },
          { label: "The Silver Line corporate corridor" },
          { label: "Tysons West and Tysons East" },
        ],
      },
      {
        region: "Related Pages",
        places: [
          { label: "Tysons Corner Limo Service", to: "/tysons-corner-limo-service" },
          { label: "BWI Corporate Transportation", to: "/bwi-corporate-transportation" },
          { label: "DCA to Tysons", to: "/dca-to-tysons" },
          { label: "Executive Car Service Virginia", to: "/executive-car-service-virginia" },
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long does BWI to Tysons take?", a: "Typically 60 to 80 minutes depending on traffic and the exact Tysons address, via I-95, the Beltway and the Dulles corridor." },
      { q: "Do you offer corporate accounts for Tysons companies?", a: "Yes, with monthly consolidated invoicing, priority dispatch and standing pickups for staff and visiting clients who fly through BWI regularly." },
      { q: "Can you pick up a visiting executive who doesn't know BWI?", a: "Yes, meet & greet puts your chauffeur inside baggage claim with a name sign, for an additional charge." },
      { q: "What if the flight into BWI is delayed?", a: "We track the flight and adjust automatically. Domestic arrivals include 45 minutes of complimentary wait, international arrivals 60 minutes." },
      { q: "How much does BWI to Tysons car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your BWI to Tysons Transfer",
    ctaSubtitle: "Flat-rate executive car service for the region's busiest office corridor — call (877) 609-1919.",
  },

  "bwi-to-mclean": {
    metaTitle: "BWI to McLean, VA Car Service | 92 Limo Service",
    metaDescription: "Discreet BWI Airport to McLean, VA car service for executives and residents. Flat rate, flight tracking, 24/7 dispatch. Call (877) 609-1919.",
    eyebrow: "BWI → MCLEAN, VA",
    h1: "BWI to McLean, VA Car Service",
    subtitle: "Private chauffeured transfers between BWI Marshall Airport and McLean — flat rate, flight-tracked, and discreet for residential and executive pickups.",
    image: "/images/site/s-class.webp",
    alt: "Chauffeured luxury sedan for BWI Airport to McLean, VA car service — 92 Limo Service",
    highlightsHeading: "Discreet Service for McLean",
    intro: [
      "McLean, Virginia is one of the Washington region's most established residential and executive communities, home to corporate leadership, federal offices and quiet, tree-lined streets off Chain Bridge Road and Old Dominion Drive. 92 Limo Service provides a flat-rate, flight-tracked car service between BWI Marshall Airport and McLean built around discretion and reliability.",
      "The drive from BWI to McLean typically takes 65 to 85 minutes, crossing the Baltimore-Washington Parkway or I-95, the Capital Beltway (I-495), and Route 123 depending on the exact destination. Because this is a longer regional trip, we quote it as a confirmed flat rate so there is no ambiguity about cost before you book.",
      "McLean's residents and executives value privacy as much as punctuality, and our chauffeurs are trained accordingly — licensed, background-checked, and discreet about who they drive and where. Corporate accounts are available for McLean-based companies and households with standing airport travel, including monthly invoicing.",
      "Every BWI to McLean pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international arrivals. Meet & greet inside baggage claim is available for an additional charge for travelers who prefer not to navigate the terminal alone.",
      "The rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Whether it is a discreet sedan pickup for one traveler or an SUV for a family with luggage, tell us your flight and McLean address and we will have a chauffeur ready.",
    ],
    highlights: [
      { title: "65–85 Minute Trip", desc: "A longer regional run via I-95, the Beltway and Route 123, quoted as a flat rate before you ride." },
      { title: "Residential Discretion", desc: "Licensed, background-checked chauffeurs trained for quiet, private pickups in McLean's residential streets." },
      { title: "Executive Accounts Available", desc: "Monthly invoicing and standing pickups for McLean companies and households with regular airport travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Meet & Greet Option", desc: "A name-sign pickup inside baggage claim, for an additional charge." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride, with no meter and no surge." },
    ],
    vehicles: [
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
      "Luxury SUV — Chevrolet Suburban",
    ],
    areas: [
      {
        region: "McLean Areas We Serve",
        places: [
          { label: "Chain Bridge Road corridor" },
          { label: "Old Dominion Drive residential area" },
          { label: "Downtown McLean" },
        ],
      },
      {
        region: "Related Pages",
        places: [
          { label: "McLean, VA Limo Service", to: "/mclean-va-limo-service" },
          { label: "BWI Corporate Transportation", to: "/bwi-corporate-transportation" },
          { label: "DCA to McLean", to: "/dca-to-mclean" },
          { label: "Executive Car Service Maryland", to: "/executive-car-service-maryland" },
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long is the drive from BWI to McLean?", a: "Typically 65 to 85 minutes depending on traffic, via I-95, the Beltway and Route 123." },
      { q: "Is the service discreet for residential pickups?", a: "Yes. Chauffeurs are licensed, background-checked and trained for the privacy McLean residents and executives expect." },
      { q: "Do you offer accounts for McLean households or companies?", a: "Yes, with monthly consolidated invoicing and standing pickups for regular airport travel." },
      { q: "What if my BWI flight is delayed?", a: "Your chauffeur tracks the flight and adjusts automatically, with complimentary wait time of 45 minutes domestic and 60 minutes international." },
      { q: "How much does BWI to McLean car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your BWI to McLean Transfer",
    ctaSubtitle: "Discreet, flat-rate chauffeur service — call (877) 609-1919 or reserve online.",
  },

  "bwi-airport-meet-and-greet": {
    metaTitle: "BWI Airport Meet and Greet Service | 92 Limo",
    metaDescription: "BWI meet and greet chauffeur service — name-sign pickup inside baggage claim, luggage help, flight tracking for domestic and international arrivals.",
    eyebrow: "BWI ARRIVALS",
    h1: "BWI Airport Meet and Greet Service",
    subtitle: "Your chauffeur waits inside baggage claim with a name sign, tracks your flight from departure, and carries your bags to the car — for domestic and international BWI arrivals alike.",
    image: "/images/site/airport-pickup.webp",
    alt: "Chauffeur holding a name sign for BWI Airport meet and greet service — 92 Limo Service",
    highlightsHeading: "What Meet & Greet Actually Includes",
    intro: [
      "Meet and greet is the difference between scanning a curb full of black cars and having your chauffeur find you first. With 92 Limo Service's BWI meet and greet, your chauffeur waits inside baggage claim holding a personalized name sign, helps with your luggage from the carousel to the vehicle, and walks you out — available for an additional charge on any BWI pickup.",
      "The service works the same way for both domestic and international arrivals, with one key difference: timing. Domestic arrivals at BWI typically move from gate to baggage claim quickly, so your chauffeur is positioned and waiting well ahead of the standard 45-minute complimentary wait window. International arrivals involve customs and immigration, which can take longer and vary by flight volume — our international meet and greet accounts for that, with 60 minutes of complimentary wait built in and a chauffeur who tracks the process rather than guessing at it.",
      "Flight tracking is included on every BWI pickup, meet and greet or not. We monitor your flight from departure, so an early landing or a late one both adjust your chauffeur's arrival automatically — you never need to call and explain a delay.",
      "Meet and greet is especially useful for first-time visitors to BWI, international travelers navigating an unfamiliar customs process, business travelers arriving with a heavy bag and a laptop, families with children, and anyone who would rather not manage curbside pickup logistics after a long flight.",
      "Add meet and greet when you book, or call ahead of your trip to add it to an existing reservation. The additional charge is disclosed and confirmed before your card is charged, alongside the rest of your quote.",
    ],
    highlights: [
      { title: "Name-Sign Pickup Inside", desc: "Your chauffeur waits in baggage claim, not the curb, holding a personalized sign so you find each other immediately." },
      { title: "Domestic and International", desc: "Available for both arrival types, with the international wait window sized for customs and immigration timing." },
      { title: "Luggage Handled", desc: "Your chauffeur carries bags from the carousel to the vehicle, no juggling required." },
      { title: "Flight Tracking Included", desc: "Monitored from departure, so an early or late landing adjusts your pickup automatically." },
      { title: "45–60 Minutes Complimentary Wait", desc: "45 minutes on domestic arrivals, 60 on international, timed from actual touchdown." },
      { title: "Add It Anytime", desc: "Include meet & greet when you book, or call ahead to add it to an existing reservation." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "Premium SUV — Cadillac Escalade",
      "Sprinter Shuttle — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "BWI Airport Transportation", to: "/bwi-airport-transportation" },
          { label: "BWI 24 Hour Car Service", to: "/bwi-24-hour-airport-car-service" },
          { label: "DCA Airport Meet and Greet", to: "/dca-airport-meet-and-greet" },
          { label: "BWI Corporate Transportation", to: "/bwi-corporate-transportation" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "What does BWI meet and greet actually include?", a: "Your chauffeur waits inside baggage claim with a personalized name sign, helps carry your luggage, and walks with you to the vehicle. It is an additional charge on top of the base transportation fare." },
      { q: "Does meet and greet work for international arrivals?", a: "Yes. International arrivals include a 60-minute complimentary wait window to account for customs and immigration, and your chauffeur tracks the flight and the general arrivals process rather than guessing." },
      { q: "How is meet and greet different from a regular curbside pickup?", a: "Curbside pickup has your chauffeur waiting outside; meet and greet puts them inside baggage claim with a name sign, which is useful if you are unfamiliar with the airport or traveling with a lot of luggage." },
      { q: "Can I add meet and greet after I've already booked?", a: "Yes, call ahead of your trip and we will add it to your existing reservation, with the additional charge confirmed before your card is charged." },
      { q: "How much does BWI meet and greet cost?", a: "It is an additional charge on top of your base fare, disclosed and confirmed before you ride — call (877) 609-1919 or ask when you book online for the exact amount." },
    ],
    ctaTitle: "Add Meet & Greet to Your BWI Pickup",
    ctaSubtitle: "Book online or call (877) 609-1919 — your chauffeur will be waiting inside with your name.",
  },

  "bwi-24-hour-airport-car-service": {
    metaTitle: "BWI 24 Hour Airport Car Service | 92 Limo",
    metaDescription: "24/7 BWI airport car service for early-morning departures and late-night arrivals. Flat rate, flight tracking, always-staffed dispatch. (877) 609-1919.",
    eyebrow: "BWI · 24/7 DISPATCH",
    h1: "BWI 24 Hour Airport Car Service",
    subtitle: "Dispatch never closes. Whether your flight leaves before sunrise or lands after midnight, a confirmed chauffeur is waiting — every day of the year.",
    image: "/images/site/night-drive.webp",
    alt: "Chauffeured vehicle for BWI Airport early morning and late night car service — 92 Limo Service",
    highlightsHeading: "Built for the Hours Other Rides Struggle With",
    intro: [
      "BWI's first departure bank rolls out before 6 a.m., and its last arrivals can land well past midnight — exactly the hours when improvised transportation is least reliable. 92 Limo Service runs 24-hour dispatch, 365 days a year, so an early-morning departure or a late-night arrival gets the same confirmed, flat-rate chauffeur as a midday trip.",
      "Pre-dawn departures are booked the night before, with your chauffeur committed and the vehicle staged ahead of time rather than assembled at the last minute. We calculate the pickup from your flight time and typical traffic for that hour, factoring in whether early-morning construction or lane closures affect the route to BWI.",
      "Late-night arrivals work the same way in reverse: your chauffeur tracks the flight, and if it lands after midnight or runs late into the early hours, the pickup adjusts automatically. Airport pickups include 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international, timed from actual touchdown regardless of the hour.",
      "This matters most for travelers in the suburbs, where rideshare driver availability tends to thin out overnight. A reservation with 92 Limo Service is committed in advance, not dependent on who happens to be nearby at 4:30 in the morning.",
      "Dispatch is staffed around the clock, so a flight change at 3 a.m. still reaches a live person, not a hold queue. Book online anytime or call (877) 609-1919 — the rate is confirmed before you ride, with gratuity, tolls and parking disclosed before confirmation, no matter the hour.",
    ],
    highlights: [
      { title: "Dispatch Staffed 24/7", desc: "A live person answers day or night, 365 days a year, for bookings and changes alike." },
      { title: "Early Departures Confirmed Ahead", desc: "Pre-dawn pickups are staged the night before, not assembled at the last minute." },
      { title: "Late Arrivals Fully Tracked", desc: "Flight tracking and complimentary wait time apply the same after midnight as at noon." },
      { title: "Reliable When Rideshare Thins Out", desc: "Your chauffeur is committed in advance, not dependent on overnight driver availability nearby." },
      { title: "Flat Rate Any Hour", desc: "The same confirmed pricing structure applies around the clock — no overnight surcharge guesswork." },
      { title: "365 Days a Year", desc: "Holidays, weekends and red-eye flights are handled the same as any other day." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "Luxury SUV — Chevrolet Suburban",
      "Sprinter Shuttle — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "BWI Airport Meet and Greet", to: "/bwi-airport-meet-and-greet" },
          { label: "BWI Airport Car Service", to: "/bwi-airport-car-service" },
          { label: "BWI Corporate Transportation", to: "/bwi-corporate-transportation" },
          { label: "BWI Airport Transportation", to: "/bwi-airport-transportation" },
          { label: "Booking & Cancellation Policies", to: "/policies" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "Is BWI car service actually available at any hour?", a: "Yes. Dispatch and reservations run 24 hours a day, 365 days a year, including holidays and overnight." },
      { q: "How early should I book a pre-dawn departure?", a: "As far ahead as you can, ideally the day before, so your chauffeur is confirmed and the vehicle is staged rather than arranged last minute." },
      { q: "What if my flight lands well after midnight?", a: "Your chauffeur is tracking the flight and adjusts the pickup automatically, with the standard complimentary wait window still applying." },
      { q: "Is rideshare a safer bet than a reserved car for overnight trips?", a: "Rideshare driver availability can thin out overnight in the suburbs; a reserved chauffeur is committed in advance rather than dependent on who is nearby at that hour." },
      { q: "How much does overnight or early-morning BWI service cost?", a: "The same flat-rate pricing structure applies around the clock, confirmed before you ride — call (877) 609-1919 or book online." },
    ],
    ctaTitle: "Book BWI Service for Any Hour",
    ctaSubtitle: "Early flight or late arrival — call (877) 609-1919 or book online, 24/7.",
  },

  "bwi-corporate-transportation": {
    metaTitle: "BWI Corporate Transportation | 92 Limo Service",
    metaDescription: "BWI corporate transportation with monthly invoicing, standing pickups and flight-tracked chauffeurs for business travelers. Call (877) 609-1919.",
    eyebrow: "BWI · CORPORATE ACCOUNTS",
    h1: "BWI Corporate Transportation",
    subtitle: "A standing account for BWI airport transfers, client pickups and roadshows — built around consolidated invoicing and dispatch that already knows your travel pattern.",
    image: "/images/site/corporate.webp",
    alt: "Executive stepping into a chauffeured vehicle for BWI corporate transportation — 92 Limo Service",
    highlightsHeading: "Built for Travel Managers, Not One-Off Rides",
    intro: [
      "Individual employees booking their own rides for BWI airport trips creates two problems for a travel manager: no consolidated record of who traveled where, and no accountability if a driver cancels an executive's pickup an hour before a flight. 92 Limo Service's corporate transportation program solves both with a standing account built around BWI travel specifically.",
      "Opening an account starts with a short conversation about your company's travel patterns — how often staff fly through BWI, whether DCA or IAD coverage matters too, and whether trips are mostly airport transfers or include client roadshows and multi-stop days. From there we set up monthly consolidated invoicing, so individual trips do not require an expense report and a personal card.",
      "Most corporate accounts designate a small group of authorized bookers — an executive assistant, an office manager, or the traveler directly — which keeps the account controlled and gives dispatch one or two reliable points of contact. For executives with predictable travel, a standing pickup arrangement reserves the same vehicle class without rebooking each time.",
      "Every chauffeur on a corporate account is licensed and background-checked, and every vehicle is commercially insured — the baseline duty-of-care standard most corporate travel policies expect. Flight tracking on BWI pickups means a delayed flight never turns into a stranded executive, and dispatch is reachable 24/7 for changes.",
      "Monthly consolidated invoicing gives an itemized record by traveler and trip, which makes reconciling against expense policy straightforward. If your company is flying through BWI regularly enough that airport transportation has become its own small administrative headache, call and ask for corporate accounts — setup is usually a same-week process.",
    ],
    highlights: [
      { title: "Monthly Consolidated Invoicing", desc: "One itemized invoice by traveler and trip, instead of scattered individual receipts and expense reports." },
      { title: "Standing Pickups", desc: "Recurring travel is set up once, without rebooking the same executive's trip each time." },
      { title: "Priority Dispatch", desc: "Corporate accounts get priority handling for airport transfers and last-minute changes." },
      { title: "Duty of Care Standard", desc: "Licensed, background-checked chauffeurs and commercially insured vehicles on every trip." },
      { title: "Roadshow & Multi-Stop Support", desc: "Hourly, as-directed service covers client visits and multi-meeting days, not just one-way transfers." },
      { title: "BWI, DCA and IAD Coverage", desc: "One account covers all three regional airports, not just BWI." },
    ],
    vehicles: [
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
      "Sprinter Executive — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "Corporate Transportation", to: "/corporate-transportation" },
          { label: "Executive Car Service Maryland", to: "/executive-car-service-maryland" },
          { label: "BWI Airport Meet and Greet", to: "/bwi-airport-meet-and-greet" },
          { label: "BWI 24 Hour Car Service", to: "/bwi-24-hour-airport-car-service" },
          { label: "Corporate Car Service DC", to: "/corporate-car-service-dc" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long does it take to set up a BWI corporate account?", a: "Usually a short conversation about your travel patterns is enough to get started, with monthly invoicing active from the first trip." },
      { q: "Can we limit who is authorized to book on the account?", a: "Yes. Most companies designate a small group of authorized bookers — an assistant, an office manager, or specific travelers — to keep the account controlled." },
      { q: "Do you offer standing pickups for an executive who flies weekly?", a: "Yes, recurring travel can be set up as a standing arrangement so the trip does not need to be rebooked each time." },
      { q: "Does the account cover DCA and IAD too, or just BWI?", a: "One corporate account covers all three regional airports, so you are not managing separate arrangements for each." },
      { q: "Is the invoice itemized by traveler?", a: "Yes, monthly consolidated invoicing breaks down travel by traveler and trip for straightforward expense reconciliation." },
    ],
    ctaTitle: "Set Up Your BWI Corporate Account",
    ctaSubtitle: "Call (877) 609-1919 and ask for corporate accounts — most setups are complete within the week.",
  },

  "dca-to-georgetown": {
    metaTitle: "DCA to Georgetown Car Service | 92 Limo Service",
    metaDescription: "Reagan National (DCA) to Georgetown car service — flat rate, flight tracking, chauffeurs who know the Key Bridge and M Street. (877) 609-1919.",
    eyebrow: "DCA → GEORGETOWN, DC",
    h1: "DCA to Georgetown Car Service",
    subtitle: "One of the shortest airport transfers in the region — Reagan National to Georgetown's rowhouses, waterfront and M Street corridor, flat rate and flight-tracked.",
    image: "/images/site/sedan.webp",
    alt: "Chauffeured sedan for Reagan National Airport to Georgetown car service — 92 Limo Service",
    highlightsHeading: "A Route Our Chauffeurs Know Well",
    intro: [
      "Georgetown has no Metro station, which makes a reserved car service one of the most practical ways to reach it from Reagan National Airport (DCA) — especially with luggage, in bad weather, or on a schedule. 92 Limo Service runs this route often: DCA sits only a few miles from Georgetown, reached via the George Washington Parkway and the Key Bridge, or the Roosevelt Bridge from the Foggy Bottom side.",
      "The trip typically takes 15 to 25 minutes depending on traffic on M Street and the bridges, which can back up at peak hours. Our chauffeurs know the neighborhood's narrow, often one-way streets and plan where to stop rather than idling in front of a rowhouse that cannot accommodate a parked car.",
      "Georgetown University visits, hotel stays along the waterfront or M Street, weddings at the neighborhood's historic venues, and simple business or leisure trips are all routine for us on this route. We also serve Georgetown's hotel entrances directly, each with its own drop-off arrangement our chauffeurs are familiar with.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge, useful for visitors unfamiliar with Reagan National's compact terminal layout.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight and Georgetown address, and we will have a chauffeur ready.",
    ],
    highlights: [
      { title: "One of the Shortest Airport Runs", desc: "Just a few miles via the GW Parkway and the Key Bridge, typically 15–25 minutes." },
      { title: "No Metro Station Nearby", desc: "Georgetown has no Metro stop, which makes a reserved car service one of the more practical options with luggage." },
      { title: "Local Street Knowledge", desc: "Chauffeurs who know Georgetown's narrow one-way streets and where to stop safely." },
      { title: "University & Hotel Pickups", desc: "Regular service for Georgetown University visits and the waterfront and M Street hotel corridor." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride, regardless of bridge traffic." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Limo", to: "/dca-airport-limo" },
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "DCA to Arlington", to: "/dca-to-arlington" },
          { label: "DCA to Alexandria", to: "/dca-to-alexandria" },
          { label: "Washington DC Limo Service", to: "/washington-dc-limo-service" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long is the drive from DCA to Georgetown?", a: "Typically 15 to 25 minutes depending on traffic on M Street and the bridges, using the GW Parkway and the Key Bridge or the Roosevelt Bridge." },
      { q: "Why book a car service instead of the Metro for Georgetown?", a: "Georgetown has no Metro station, so a reserved car is often the more practical option, especially with luggage or in bad weather." },
      { q: "Can you pick up at a Georgetown hotel?", a: "Yes, our chauffeurs are familiar with the entrances and drop-off arrangements at hotels along the waterfront and M Street." },
      { q: "Do you serve Georgetown University visits?", a: "Yes, including tours, move-in and family weekend transportation from DCA." },
      { q: "How much does DCA to Georgetown car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to Georgetown Transfer",
    ctaSubtitle: "Flat rate, flight-tracked, and familiar with Georgetown's streets — call (877) 609-1919.",
  },

  "dca-to-arlington": {
    metaTitle: "DCA to Arlington Car Service | 92 Limo Service",
    metaDescription: "Reagan National (DCA) to Arlington, VA car service — Crystal City, Rosslyn, Pentagon City. Flat rate, flight tracking. Call (877) 609-1919.",
    eyebrow: "DCA → ARLINGTON, VA",
    h1: "DCA to Arlington Car Service",
    subtitle: "A short, flat-rate ride to Crystal City, Rosslyn, Pentagon City and the rest of Arlington — Reagan National sits practically next door.",
    image: "/images/site/suv.webp",
    alt: "Chauffeured SUV for Reagan National Airport to Arlington, VA car service — 92 Limo Service",
    highlightsHeading: "Arlington's Closest Airport, Handled Right",
    intro: [
      "Arlington, Virginia sits directly across the Potomac from Reagan National Airport, and neighborhoods like Crystal City and National Landing are close enough that the drive is measured in minutes. 92 Limo Service runs flat-rate, flight-tracked transfers between DCA and Arlington's corporate towers, residential corridors and Pentagon-adjacent offices.",
      "The trip typically takes 5 to 20 minutes depending on your exact Arlington destination and traffic, using the George Washington Parkway or Route 1. Because the airport is so close, this is exactly the kind of trip where a reserved, flight-tracked pickup matters most — with so little buffer built in naturally, a confirmed chauffeur removes the risk of the last mile going wrong.",
      "Arlington's office towers along Crystal Drive and the Rosslyn-Ballston corridor generate steady corporate travel, and we run standing pickups and client transfers for companies headquartered there. Pentagon and Pentagon City trips are routine as well, often combined with an airport transfer on the same reservation.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Whether it is a quick executive sedan pickup or an SUV for a family with luggage, tell us your flight and Arlington address and we will have a chauffeur ready.",
    ],
    highlights: [
      { title: "5–20 Minute Trip", desc: "One of the shortest airport transfers we offer, via the GW Parkway or Route 1." },
      { title: "Crystal City & National Landing", desc: "Regular service to Arlington's corporate towers and the Amazon HQ2 corridor." },
      { title: "Rosslyn & Pentagon City", desc: "Familiar with the Rosslyn-Ballston corridor and Pentagon-adjacent trips." },
      { title: "Corporate Accounts Available", desc: "Standing pickups and monthly invoicing for Arlington companies with regular DCA travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Flat Rate, No Surprises", desc: "One confirmed price before you ride, even on this short a trip." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Limo", to: "/dca-airport-limo" },
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "DCA to Alexandria", to: "/dca-to-alexandria" },
          { label: "DCA to Georgetown", to: "/dca-to-georgetown" },
          { label: "Corporate Limo DC", to: "/corporate-limo-dc" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How close is Arlington to Reagan National?", a: "Very close — trips to Crystal City and National Landing typically run 5 to 15 minutes, with the rest of Arlington usually under 20 minutes depending on traffic." },
      { q: "Do you serve corporate offices in Crystal City?", a: "Yes, including standing accounts with monthly invoicing for companies along Crystal Drive and the surrounding corridor." },
      { q: "Can you combine a Pentagon trip with an airport transfer?", a: "Yes, Pentagon and Pentagon City stops are often combined with a DCA transfer on the same reservation." },
      { q: "What if my flight into DCA is delayed?", a: "Your chauffeur tracks the flight and adjusts the pickup automatically, with 45 minutes of complimentary wait on domestic arrivals." },
      { q: "How much does DCA to Arlington car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to Arlington Transfer",
    ctaSubtitle: "One of our shortest routes, still flat-rate and flight-tracked — call (877) 609-1919.",
  },

  "dca-to-alexandria": {
    metaTitle: "DCA to Alexandria Car Service | 92 Limo Service",
    metaDescription: "Reagan National (DCA) to Alexandria, VA car service — Old Town, King Street, Del Ray. Flat rate, flight tracking, 24/7. Call (877) 609-1919.",
    eyebrow: "DCA → ALEXANDRIA, VA",
    h1: "DCA to Alexandria Car Service",
    subtitle: "Chauffeured transfers between Reagan National Airport and Old Town Alexandria's King Street, waterfront and Del Ray — flat rate and flight-tracked.",
    image: "/images/site/sedan.webp",
    alt: "Chauffeured sedan for Reagan National Airport to Alexandria, VA car service — 92 Limo Service",
    highlightsHeading: "Old Town's Preferred Car Service",
    intro: [
      "Alexandria, Virginia sits just south of Reagan National Airport along the George Washington Parkway, close enough that a transfer to Old Town's King Street or the waterfront rarely takes more than 20 minutes. 92 Limo Service runs flat-rate, flight-tracked car service on this route for visitors, residents and businesses throughout Alexandria.",
      "The trip typically takes 10 to 20 minutes depending on traffic and your exact Alexandria destination, using the GW Parkway or Route 1. Old Town's brick sidewalks, cobblestone side streets and limited parking make a reserved chauffeur especially practical for hotel guests and residents alike.",
      "Beyond Old Town, we regularly serve Del Ray, Carlyle and the West End, including corporate offices with standing accounts and weddings at Alexandria's historic venues along the waterfront. Cruise passengers connecting through Alexandria hotels before or after a trip also use this route often.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge, useful for guests unfamiliar with Reagan National.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight and Alexandria address, and a chauffeur will be ready.",
    ],
    highlights: [
      { title: "10–20 Minute Trip", desc: "A short, flat-rate run via the GW Parkway or Route 1, just south of DCA." },
      { title: "Old Town & King Street", desc: "Chauffeurs familiar with Old Town's brick streets, limited parking, and hotel entrances." },
      { title: "Del Ray, Carlyle & the West End", desc: "Coverage across all of Alexandria, not just the historic district." },
      { title: "Weddings & Waterfront Venues", desc: "Regular service to Alexandria's historic wedding and event venues." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride, no meter running through Old Town traffic." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "First Class Sedan — BMW 7 Series",
      "Sprinter Shuttle — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Limo", to: "/dca-airport-limo" },
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "DCA to Arlington", to: "/dca-to-arlington" },
          { label: "Wedding Car Service DC", to: "/wedding-car-service-dc" },
          { label: "Cruise Transfers", to: "/cruise-transfers" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long is the drive from DCA to Old Town Alexandria?", a: "Typically 10 to 20 minutes depending on traffic, using the GW Parkway or Route 1." },
      { q: "Why use a car service instead of driving in Old Town?", a: "Old Town's brick streets and limited parking make a reserved chauffeur practical, especially for hotel guests with luggage." },
      { q: "Do you serve Del Ray and Carlyle as well as Old Town?", a: "Yes, we cover all of Alexandria, including corporate accounts for offices in Carlyle and the West End." },
      { q: "Can you provide wedding transportation to Alexandria's waterfront venues?", a: "Yes, we regularly serve Alexandria's historic wedding venues with sedans, SUVs and Sprinter vans." },
      { q: "How much does DCA to Alexandria car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to Alexandria Transfer",
    ctaSubtitle: "Flat rate, flight-tracked, and familiar with Old Town — call (877) 609-1919.",
  },

  "dca-to-tysons": {
    metaTitle: "DCA to Tysons Car Service | 92 Limo Service",
    metaDescription: "Reagan National (DCA) to Tysons, VA car service for executives. Flat rate, flight tracking, corporate accounts. Call (877) 609-1919.",
    eyebrow: "DCA → TYSONS, VA",
    h1: "DCA to Tysons Car Service",
    subtitle: "Chauffeured transfers between Reagan National Airport and Tysons' corporate corridor — flat rate, flight-tracked, with standing accounts for executive travel.",
    image: "/images/site/s-class.webp",
    alt: "Chauffeured executive sedan for Reagan National Airport to Tysons, VA car service — 92 Limo Service",
    highlightsHeading: "The Airport-to-Office Route Tysons Companies Rely On",
    intro: [
      "DCA is the closest-in of the three regional airports, and for Tysons-based executives and companies, it is often the fastest way to move visiting clients and staff in and out. 92 Limo Service runs flat-rate, flight-tracked car service between Reagan National and Tysons' office towers, Tysons Corner Center and the Silver Line corridor.",
      "The trip typically takes 25 to 40 minutes depending on traffic, using the GW Parkway, I-395 and the Dulles Toll Road or Route 123. This is a shorter, more predictable trip than the same run from Dulles or BWI, which is one reason many Tysons companies default to DCA for domestic client and staff travel.",
      "Corporate accounts are common on this route: standing pickups for executives with predictable schedules, monthly consolidated invoicing, and priority dispatch for visiting clients who need a reliable, professional first impression straight from the airport.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge for visiting executives unfamiliar with the terminal.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight and Tysons destination and a chauffeur will be ready.",
    ],
    highlights: [
      { title: "25–40 Minute Trip", desc: "A shorter, more predictable run than from Dulles or BWI, via the GW Parkway and I-395." },
      { title: "Corporate HQ Corridor", desc: "Regular service to Tysons Corner Center, Tysons Galleria and the Silver Line office towers." },
      { title: "Standing Executive Accounts", desc: "Monthly invoicing and priority dispatch for Tysons companies with regular staff or client travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Meet & Greet for Visitors", desc: "A name-sign pickup inside baggage claim for guests unfamiliar with DCA, for an additional charge." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride, regardless of traffic." },
    ],
    vehicles: [
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
      "Sprinter Executive — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "BWI to Tysons", to: "/bwi-to-tysons" },
          { label: "DCA to McLean", to: "/dca-to-mclean" },
          { label: "Tysons Corner Limo Service", to: "/tysons-corner-limo-service" },
          { label: "Executive Car Service Virginia", to: "/executive-car-service-virginia" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long does DCA to Tysons take?", a: "Typically 25 to 40 minutes depending on traffic, using the GW Parkway, I-395 and the Dulles Toll Road or Route 123 — usually shorter than the same run from Dulles or BWI." },
      { q: "Why do Tysons companies prefer DCA for client travel?", a: "DCA is the closest-in regional airport, which generally means a shorter, more predictable trip for domestic travelers." },
      { q: "Do you offer corporate accounts for Tysons companies?", a: "Yes, with monthly consolidated invoicing, priority dispatch and standing pickups for staff and visiting clients." },
      { q: "Can you meet a visiting executive who doesn't know DCA?", a: "Yes, meet & greet puts your chauffeur inside baggage claim with a name sign, for an additional charge." },
      { q: "How much does DCA to Tysons car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to Tysons Transfer",
    ctaSubtitle: "The shorter, flat-rate route for Tysons executive travel — call (877) 609-1919.",
  },

  "dca-to-mclean": {
    metaTitle: "DCA to McLean, VA Car Service | 92 Limo Service",
    metaDescription: "Discreet Reagan National (DCA) to McLean, VA car service for residents and executives. Flat rate, flight tracking. Call (877) 609-1919.",
    eyebrow: "DCA → MCLEAN, VA",
    h1: "DCA to McLean, VA Car Service",
    subtitle: "Private chauffeured transfers between Reagan National Airport and McLean — flat rate, flight-tracked, and discreet for residential and executive pickups.",
    image: "/images/site/s-class.webp",
    alt: "Chauffeured luxury sedan for Reagan National Airport to McLean, VA car service — 92 Limo Service",
    highlightsHeading: "The Region's Closer Airport for McLean",
    intro: [
      "McLean, Virginia's residents and executives often prefer Reagan National for domestic travel, since it is closer than Dulles for many trips and avoids the mid-field concourse walk that comes with a larger airport. 92 Limo Service runs flat-rate, discreet car service between DCA and McLean's quiet residential streets and corporate offices.",
      "The trip typically takes 25 to 35 minutes depending on traffic, using the GW Parkway, I-495 and Route 123. As with our BWI-to-McLean route, privacy matters as much as punctuality here, and our chauffeurs are trained to be quiet and professional on McLean's residential streets.",
      "Corporate accounts are available for McLean-based companies and households with standing airport travel, including monthly invoicing and priority dispatch. This route also sees regular use from executives who split their travel between DCA and Dulles depending on the destination.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight and McLean address and a chauffeur will be ready.",
    ],
    highlights: [
      { title: "25–35 Minute Trip", desc: "Often the closer airport choice for McLean, via the GW Parkway, I-495 and Route 123." },
      { title: "Residential Discretion", desc: "Licensed, background-checked chauffeurs trained for quiet, private pickups in McLean's neighborhoods." },
      { title: "Executive Accounts Available", desc: "Monthly invoicing and standing pickups for McLean companies and households with regular airport travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Meet & Greet Option", desc: "A name-sign pickup inside baggage claim, for an additional charge." },
      { title: "Flat Rate, Confirmed First", desc: "One transparent price before you ride, with no meter and no surge." },
    ],
    vehicles: [
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
      "Luxury SUV — Chevrolet Suburban",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "BWI to McLean", to: "/bwi-to-mclean" },
          { label: "DCA to Tysons", to: "/dca-to-tysons" },
          { label: "McLean, VA Limo Service", to: "/mclean-va-limo-service" },
          { label: "Executive Car Service Maryland", to: "/executive-car-service-maryland" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "Is DCA closer to McLean than Dulles?", a: "For many McLean trips, yes — DCA is often the shorter, more predictable option, though the best airport depends on your specific flight." },
      { q: "Is the service discreet for residential pickups in McLean?", a: "Yes. Chauffeurs are licensed, background-checked and trained for the privacy McLean residents and executives expect." },
      { q: "Do you offer accounts for McLean households or companies?", a: "Yes, with monthly consolidated invoicing and standing pickups for regular airport travel." },
      { q: "What if my DCA flight is delayed?", a: "Your chauffeur tracks the flight and adjusts automatically, with 45 minutes of complimentary wait on domestic arrivals." },
      { q: "How much does DCA to McLean car service cost?", a: "It is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, with gratuity, tolls and parking disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to McLean Transfer",
    ctaSubtitle: "Discreet, flat-rate chauffeur service — call (877) 609-1919 or reserve online.",
  },

  "dca-to-silver-spring": {
    metaTitle: "DCA to Silver Spring Car Service | 92 Limo Service",
    metaDescription: "Flat-rate Reagan National (DCA) to Silver Spring, MD car service. Flight tracking, meet & greet available, 24/7. Call (877) 609-1919.",
    eyebrow: "DCA → SILVER SPRING, MD",
    h1: "DCA to Silver Spring Car Service",
    subtitle: "Chauffeured transfers between Reagan National Airport and Silver Spring's Downtown and Discovery District — flat rate, flight-tracked, 24/7.",
    image: "/images/site/suv.webp",
    alt: "Chauffeured SUV for Reagan National Airport to Silver Spring, MD car service — 92 Limo Service",
    highlightsHeading: "Crossing the District, Handled Right",
    intro: [
      "Silver Spring sits on the opposite side of Washington DC from Reagan National, which makes this trip one of the longer cross-district routes we run — and exactly why a flat, confirmed rate matters more than a meter that climbs with every red light on Georgia Avenue or 16th Street.",
      "The drive from DCA to Silver Spring typically takes 35 to 55 minutes, depending on the route through the District or around the Beltway and the time of day. Rush hour on either path can add real time, so we back-time pickups against current conditions rather than a flat assumption.",
      "Silver Spring's Discovery District offices and downtown corridor generate steady corporate travel to DCA, and we support that with standing accounts and monthly invoicing. Families and groups also use this route for weddings, proms and event travel connecting Silver Spring to destinations across the region.",
      "Every DCA pickup includes real-time flight tracking, with 45 minutes of complimentary waiting time on domestic arrivals and 60 minutes on international. Meet & greet inside baggage claim is available for an additional charge.",
      "Your rate is confirmed before you ride and covers the base transportation charge, with gratuity, tolls and parking disclosed before confirmation. Tell us your flight and Silver Spring address and a chauffeur will be ready.",
    ],
    highlights: [
      { title: "35–55 Minute Trip", desc: "A cross-district run through DC or around the Beltway, timed against real traffic conditions." },
      { title: "Downtown & Discovery District", desc: "Chauffeurs who know Silver Spring's offices, apartments and the AFI Silver Theatre corridor." },
      { title: "Corporate Accounts Available", desc: "Monthly invoicing and priority dispatch for Silver Spring businesses with regular DCA travel." },
      { title: "Flight Tracking Included", desc: "45–60 minutes of complimentary wait time built into every airport fare." },
      { title: "Meet & Greet Option", desc: "A name-sign pickup inside baggage claim, for an additional charge." },
      { title: "Flat Rate, No Surge", desc: "One confirmed price before you ride, regardless of the route or traffic." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "Luxury SUV — Chevrolet Suburban",
      "Sprinter Executive — Mercedes Sprinter",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "BWI to Silver Spring", to: "/bwi-to-silver-spring" },
          { label: "Silver Spring Limo Service", to: "/silver-spring-limo-service" },
          { label: "DCA to Bethesda", to: "/dca-to-bethesda" },
          { label: "Washington DC Limo Service", to: "/washington-dc-limo-service" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "How long is the drive from DCA to Silver Spring?", a: "Typically 35 to 55 minutes depending on the route through DC or around the Beltway and the time of day." },
      { q: "Do you serve the Discovery District and downtown offices?", a: "Yes, including corporate accounts with monthly invoicing for businesses in that corridor with regular airport travel." },
      { q: "Can you pick up a group heading to an event from Silver Spring?", a: "Yes. SUVs and Sprinter vans carry groups and their luggage for weddings, proms and multi-stop days." },
      { q: "What happens if my DCA arrival is delayed?", a: "Your chauffeur tracks the flight and adjusts automatically. Domestic arrivals include 45 minutes of complimentary wait." },
      { q: "What does DCA to Silver Spring car service cost?", a: "Every trip is quoted as a flat rate confirmed before you ride — call (877) 609-1919 or book online, and gratuity, tolls and parking are disclosed before confirmation." },
    ],
    ctaTitle: "Book Your DCA to Silver Spring Transfer",
    ctaSubtitle: "Flat-rate, flight-tracked chauffeur service — call (877) 609-1919 or reserve online.",
  },

  "dca-airport-meet-and-greet": {
    metaTitle: "DCA Airport Meet and Greet Service | 92 Limo",
    metaDescription: "Reagan National (DCA) meet and greet chauffeur service — name-sign pickup, luggage help, flight tracking. Call (877) 609-1919 to book.",
    eyebrow: "DCA ARRIVALS",
    h1: "DCA Airport Meet and Greet Service",
    subtitle: "Your chauffeur waits inside baggage claim with a name sign, tracks your flight from departure, and carries your bags to the car at Reagan National.",
    image: "/images/site/airport-pickup.webp",
    alt: "Chauffeur holding a name sign for Reagan National Airport meet and greet service — 92 Limo Service",
    highlightsHeading: "What DCA Meet & Greet Includes",
    intro: [
      "Reagan National is a compact, walkable airport — two terminals, a short walk to baggage claim, and none of the mid-field concourse trek that comes with a larger airport. That simplicity makes DCA meet and greet especially easy: your chauffeur waits inside baggage claim holding a personalized name sign, ready to help with luggage the moment you arrive.",
      "Because DCA operates under a long-standing perimeter rule that limits most nonstop flights to destinations within roughly 1,250 miles, the overwhelming majority of arrivals are domestic. Domestic meet and greet pickups include 45 minutes of complimentary waiting time, timed from actual touchdown, which rarely gets tested given how quickly DCA moves passengers from gate to curb.",
      "For the smaller share of international arrivals DCA does receive, the complimentary wait window extends to 60 minutes to account for immigration and customs, and your chauffeur tracks the process rather than guessing at timing.",
      "Flight tracking is included on every DCA pickup, meet and greet or not — we monitor your flight from departure, so an early or late landing both adjust your chauffeur's arrival automatically. You never need to call and explain a delay.",
      "Meet and greet is especially useful for first-time visitors to DCA, business travelers with a laptop bag and a suitcase, families, and anyone who would rather not scan a row of cars at the curb after a flight. Add it when you book, or call ahead to add it to an existing reservation — the additional charge is confirmed before your card is charged.",
    ],
    highlights: [
      { title: "Name-Sign Pickup Inside", desc: "Your chauffeur waits in baggage claim, not the curb, at Reagan National's compact terminal." },
      { title: "Simple, Fast Terminal Layout", desc: "DCA's short walk from gate to curb means most domestic pickups are quick and predictable." },
      { title: "Luggage Handled", desc: "Your chauffeur carries bags from the carousel to the vehicle." },
      { title: "Flight Tracking Included", desc: "Monitored from departure, so an early or late landing adjusts your pickup automatically." },
      { title: "45–60 Minutes Complimentary Wait", desc: "45 minutes on domestic arrivals, 60 on the smaller share of international arrivals." },
      { title: "Add It Anytime", desc: "Include meet & greet when you book, or call ahead to add it to an existing reservation." },
    ],
    vehicles: [
      "Business Sedan — Mercedes E-Class",
      "First Class Sedan — BMW 7 Series",
      "Premium SUV — Cadillac Escalade",
    ],
    areas: [
      {
        region: "Related Pages",
        places: [
          { label: "DCA Airport Car Service", to: "/dca-airport-car-service" },
          { label: "DCA Airport Limo", to: "/dca-airport-limo" },
          { label: "BWI Airport Meet and Greet", to: "/bwi-airport-meet-and-greet" },
          { label: "DCA to Georgetown", to: "/dca-to-georgetown" },
          { label: "Corporate Limo DC", to: "/corporate-limo-dc" },
          { label: "Book Online", to: "/booking" },
        ],
      },
    ],
    faqs: [
      { q: "What does DCA meet and greet include?", a: "Your chauffeur waits inside baggage claim with a personalized name sign, helps with your luggage, and walks with you to the vehicle. It is an additional charge on top of the base fare." },
      { q: "Why does DCA have fewer international meet and greet requests than other airports?", a: "A long-standing perimeter rule limits most nonstop DCA flights to destinations within roughly 1,250 miles, so the large majority of arrivals are domestic." },
      { q: "How much complimentary wait time comes with meet and greet?", a: "45 minutes on domestic arrivals and 60 minutes on international, timed from actual touchdown, whether or not you add meet and greet." },
      { q: "Can I add meet and greet after I've already booked?", a: "Yes, call ahead of your trip and we will add it to your existing reservation." },
      { q: "How much does DCA meet and greet cost?", a: "It is an additional charge on top of your base fare, disclosed and confirmed before you ride — call (877) 609-1919 or ask when you book online." },
    ],
    ctaTitle: "Add Meet & Greet to Your DCA Pickup",
    ctaSubtitle: "Book online or call (877) 609-1919 — your chauffeur will be waiting inside with your name.",
  },
};
